version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - gosec
    - revive
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: var-naming
          arguments:
            - - URL
