// Code generated by mockery v1.0.0. DO NOT EDIT.

package gocb

import (
	gocbcore "github.com/couchbase/gocbcore/v9"
	mock "github.com/stretchr/testify/mock"
)

// mockKvCapabilityVerifier is an autogenerated mock type for the kvCapabilityVerifier type
type mockKvCapabilityVerifier struct {
	mock.Mock
}

// BucketCapabilityStatus provides a mock function with given fields: cap
func (_m *mockKvCapabilityVerifier) BucketCapabilityStatus(cap gocbcore.BucketCapability) gocbcore.BucketCapabilityStatus {
	ret := _m.Called(cap)

	var r0 gocbcore.BucketCapabilityStatus
	if rf, ok := ret.Get(0).(func(gocbcore.BucketCapability) gocbcore.BucketCapabilityStatus); ok {
		r0 = rf(cap)
	} else {
		r0 = ret.Get(0).(gocbcore.BucketCapabilityStatus)
	}

	return r0
}
