// Code generated by mockery v2.46.2. DO NOT EDIT.

package gocb

import (
	search "github.com/couchbase/gocb/v2/search"
	mock "github.com/stretchr/testify/mock"
)

// mockSearchProvider is an autogenerated mock type for the searchProvider type
type mockSearchProvider struct {
	mock.Mock
}

// Search provides a mock function with given fields: scope, indexName, request, opts
func (_m *mockSearchProvider) Search(scope *Scope, indexName string, request SearchRequest, opts *SearchOptions) (*SearchResult, error) {
	ret := _m.Called(scope, indexName, request, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*Scope, string, SearchRequest, *SearchOptions) (*SearchResult, error)); ok {
		return rf(scope, indexName, request, opts)
	}
	if rf, ok := ret.Get(0).(func(*Scope, string, SearchRequest, *SearchOptions) *SearchResult); ok {
		r0 = rf(scope, indexName, request, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(*Scope, string, SearchRequest, *SearchOptions) error); ok {
		r1 = rf(scope, indexName, request, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchQuery provides a mock function with given fields: indexName, query, opts
func (_m *mockSearchProvider) SearchQuery(indexName string, query search.Query, opts *SearchOptions) (*SearchResult, error) {
	ret := _m.Called(indexName, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchQuery")
	}

	var r0 *SearchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, search.Query, *SearchOptions) (*SearchResult, error)); ok {
		return rf(indexName, query, opts)
	}
	if rf, ok := ret.Get(0).(func(string, search.Query, *SearchOptions) *SearchResult); ok {
		r0 = rf(indexName, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SearchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, search.Query, *SearchOptions) error); ok {
		r1 = rf(indexName, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockSearchProvider creates a new instance of mockSearchProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSearchProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSearchProvider {
	mock := &mockSearchProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
