// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockViewProviderCoreProvider creates a new instance of mockViewProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockViewProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockViewProviderCoreProvider {
	mock := &mockViewProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockViewProviderCoreProvider is an autogenerated mock type for the viewProviderCoreProvider type
type mockViewProviderCoreProvider struct {
	mock.Mock
}

type mockViewProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockViewProviderCoreProvider) EXPECT() *mockViewProviderCoreProvider_Expecter {
	return &mockViewProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// ViewQuery provides a mock function for the type mockViewProviderCoreProvider
func (_mock *mockViewProviderCoreProvider) ViewQuery(ctx context.Context, opts gocbcore.ViewQueryOptions) (viewRowReader, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ViewQuery")
	}

	var r0 viewRowReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.ViewQueryOptions) (viewRowReader, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.ViewQueryOptions) viewRowReader); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(viewRowReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.ViewQueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockViewProviderCoreProvider_ViewQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewQuery'
type mockViewProviderCoreProvider_ViewQuery_Call struct {
	*mock.Call
}

// ViewQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.ViewQueryOptions
func (_e *mockViewProviderCoreProvider_Expecter) ViewQuery(ctx interface{}, opts interface{}) *mockViewProviderCoreProvider_ViewQuery_Call {
	return &mockViewProviderCoreProvider_ViewQuery_Call{Call: _e.mock.On("ViewQuery", ctx, opts)}
}

func (_c *mockViewProviderCoreProvider_ViewQuery_Call) Run(run func(ctx context.Context, opts gocbcore.ViewQueryOptions)) *mockViewProviderCoreProvider_ViewQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.ViewQueryOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.ViewQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockViewProviderCoreProvider_ViewQuery_Call) Return(viewRowReaderMoqParam viewRowReader, err error) *mockViewProviderCoreProvider_ViewQuery_Call {
	_c.Call.Return(viewRowReaderMoqParam, err)
	return _c
}

func (_c *mockViewProviderCoreProvider_ViewQuery_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.ViewQueryOptions) (viewRowReader, error)) *mockViewProviderCoreProvider_ViewQuery_Call {
	_c.Call.Return(run)
	return _c
}
