// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockQueryProvider creates a new instance of mockQueryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockQueryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockQueryProvider {
	mock := &mockQueryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockQueryProvider is an autogenerated mock type for the queryProvider type
type mockQueryProvider struct {
	mock.Mock
}

type mockQueryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockQueryProvider) EXPECT() *mockQueryProvider_Expecter {
	return &mockQueryProvider_Expecter{mock: &_m.Mock}
}

// Query provides a mock function for the type mockQueryProvider
func (_mock *mockQueryProvider) Query(statement string, s *Scope, opts *QueryOptions) (*QueryResult, error) {
	ret := _mock.Called(statement, s, opts)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *QueryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *Scope, *QueryOptions) (*QueryResult, error)); ok {
		return returnFunc(statement, s, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *Scope, *QueryOptions) *QueryResult); ok {
		r0 = returnFunc(statement, s, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*QueryResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *Scope, *QueryOptions) error); ok {
		r1 = returnFunc(statement, s, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockQueryProvider_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type mockQueryProvider_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - statement string
//   - s *Scope
//   - opts *QueryOptions
func (_e *mockQueryProvider_Expecter) Query(statement interface{}, s interface{}, opts interface{}) *mockQueryProvider_Query_Call {
	return &mockQueryProvider_Query_Call{Call: _e.mock.On("Query", statement, s, opts)}
}

func (_c *mockQueryProvider_Query_Call) Run(run func(statement string, s *Scope, opts *QueryOptions)) *mockQueryProvider_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *Scope
		if args[1] != nil {
			arg1 = args[1].(*Scope)
		}
		var arg2 *QueryOptions
		if args[2] != nil {
			arg2 = args[2].(*QueryOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockQueryProvider_Query_Call) Return(queryResult *QueryResult, err error) *mockQueryProvider_Query_Call {
	_c.Call.Return(queryResult, err)
	return _c
}

func (_c *mockQueryProvider_Query_Call) RunAndReturn(run func(statement string, s *Scope, opts *QueryOptions) (*QueryResult, error)) *mockQueryProvider_Query_Call {
	_c.Call.Return(run)
	return _c
}
