// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"time"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockKvProviderCoreProvider creates a new instance of mockKvProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockKvProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockKvProviderCoreProvider {
	mock := &mockKvProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockKvProviderCoreProvider is an autogenerated mock type for the kvProviderCoreProvider type
type mockKvProviderCoreProvider struct {
	mock.Mock
}

type mockKvProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockKvProviderCoreProvider) EXPECT() *mockKvProviderCoreProvider_Expecter {
	return &mockKvProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Add(opts gocbcore.AddOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AddOptions, gocbcore.StoreCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AddOptions, gocbcore.StoreCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.AddOptions, gocbcore.StoreCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type mockKvProviderCoreProvider_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - opts gocbcore.AddOptions
//   - cb gocbcore.StoreCallback
func (_e *mockKvProviderCoreProvider_Expecter) Add(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Add_Call {
	return &mockKvProviderCoreProvider_Add_Call{Call: _e.mock.On("Add", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Add_Call) Run(run func(opts gocbcore.AddOptions, cb gocbcore.StoreCallback)) *mockKvProviderCoreProvider_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.AddOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.AddOptions)
		}
		var arg1 gocbcore.StoreCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.StoreCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Add_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Add_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Add_Call) RunAndReturn(run func(opts gocbcore.AddOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Append provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Append(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type mockKvProviderCoreProvider_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - opts gocbcore.AdjoinOptions
//   - cb gocbcore.AdjoinCallback
func (_e *mockKvProviderCoreProvider_Expecter) Append(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Append_Call {
	return &mockKvProviderCoreProvider_Append_Call{Call: _e.mock.On("Append", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Append_Call) Run(run func(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback)) *mockKvProviderCoreProvider_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.AdjoinOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.AdjoinOptions)
		}
		var arg1 gocbcore.AdjoinCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.AdjoinCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Append_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Append_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Append_Call) RunAndReturn(run func(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Decrement provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Decrement(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type mockKvProviderCoreProvider_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - opts gocbcore.CounterOptions
//   - cb gocbcore.CounterCallback
func (_e *mockKvProviderCoreProvider_Expecter) Decrement(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Decrement_Call {
	return &mockKvProviderCoreProvider_Decrement_Call{Call: _e.mock.On("Decrement", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Decrement_Call) Run(run func(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback)) *mockKvProviderCoreProvider_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.CounterOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.CounterOptions)
		}
		var arg1 gocbcore.CounterCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.CounterCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Decrement_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Decrement_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Decrement_Call) RunAndReturn(run func(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Delete(opts gocbcore.DeleteOptions, cb gocbcore.DeleteCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.DeleteOptions, gocbcore.DeleteCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.DeleteOptions, gocbcore.DeleteCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.DeleteOptions, gocbcore.DeleteCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockKvProviderCoreProvider_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - opts gocbcore.DeleteOptions
//   - cb gocbcore.DeleteCallback
func (_e *mockKvProviderCoreProvider_Expecter) Delete(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Delete_Call {
	return &mockKvProviderCoreProvider_Delete_Call{Call: _e.mock.On("Delete", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Delete_Call) Run(run func(opts gocbcore.DeleteOptions, cb gocbcore.DeleteCallback)) *mockKvProviderCoreProvider_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.DeleteOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.DeleteOptions)
		}
		var arg1 gocbcore.DeleteCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.DeleteCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Delete_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Delete_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Delete_Call) RunAndReturn(run func(opts gocbcore.DeleteOptions, cb gocbcore.DeleteCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Get(opts gocbcore.GetOptions, cb gocbcore.GetCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetOptions, gocbcore.GetCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetOptions, gocbcore.GetCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.GetOptions, gocbcore.GetCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockKvProviderCoreProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - opts gocbcore.GetOptions
//   - cb gocbcore.GetCallback
func (_e *mockKvProviderCoreProvider_Expecter) Get(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Get_Call {
	return &mockKvProviderCoreProvider_Get_Call{Call: _e.mock.On("Get", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Get_Call) Run(run func(opts gocbcore.GetOptions, cb gocbcore.GetCallback)) *mockKvProviderCoreProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.GetOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.GetOptions)
		}
		var arg1 gocbcore.GetCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.GetCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Get_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Get_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Get_Call) RunAndReturn(run func(opts gocbcore.GetOptions, cb gocbcore.GetCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndLock provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) GetAndLock(opts gocbcore.GetAndLockOptions, cb gocbcore.GetAndLockCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetAndLock")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetAndLockOptions, gocbcore.GetAndLockCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetAndLockOptions, gocbcore.GetAndLockCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.GetAndLockOptions, gocbcore.GetAndLockCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_GetAndLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndLock'
type mockKvProviderCoreProvider_GetAndLock_Call struct {
	*mock.Call
}

// GetAndLock is a helper method to define mock.On call
//   - opts gocbcore.GetAndLockOptions
//   - cb gocbcore.GetAndLockCallback
func (_e *mockKvProviderCoreProvider_Expecter) GetAndLock(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_GetAndLock_Call {
	return &mockKvProviderCoreProvider_GetAndLock_Call{Call: _e.mock.On("GetAndLock", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_GetAndLock_Call) Run(run func(opts gocbcore.GetAndLockOptions, cb gocbcore.GetAndLockCallback)) *mockKvProviderCoreProvider_GetAndLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.GetAndLockOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.GetAndLockOptions)
		}
		var arg1 gocbcore.GetAndLockCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.GetAndLockCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_GetAndLock_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_GetAndLock_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_GetAndLock_Call) RunAndReturn(run func(opts gocbcore.GetAndLockOptions, cb gocbcore.GetAndLockCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_GetAndLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndTouch provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) GetAndTouch(opts gocbcore.GetAndTouchOptions, cb gocbcore.GetAndTouchCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetAndTouch")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetAndTouchOptions, gocbcore.GetAndTouchCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetAndTouchOptions, gocbcore.GetAndTouchCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.GetAndTouchOptions, gocbcore.GetAndTouchCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_GetAndTouch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndTouch'
type mockKvProviderCoreProvider_GetAndTouch_Call struct {
	*mock.Call
}

// GetAndTouch is a helper method to define mock.On call
//   - opts gocbcore.GetAndTouchOptions
//   - cb gocbcore.GetAndTouchCallback
func (_e *mockKvProviderCoreProvider_Expecter) GetAndTouch(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_GetAndTouch_Call {
	return &mockKvProviderCoreProvider_GetAndTouch_Call{Call: _e.mock.On("GetAndTouch", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_GetAndTouch_Call) Run(run func(opts gocbcore.GetAndTouchOptions, cb gocbcore.GetAndTouchCallback)) *mockKvProviderCoreProvider_GetAndTouch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.GetAndTouchOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.GetAndTouchOptions)
		}
		var arg1 gocbcore.GetAndTouchCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.GetAndTouchCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_GetAndTouch_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_GetAndTouch_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_GetAndTouch_Call) RunAndReturn(run func(opts gocbcore.GetAndTouchOptions, cb gocbcore.GetAndTouchCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_GetAndTouch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollectionID provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) GetCollectionID(scopeName string, collectionName string, opts gocbcore.GetCollectionIDOptions, cb gocbcore.GetCollectionIDCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(scopeName, collectionName, opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionID")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, gocbcore.GetCollectionIDOptions, gocbcore.GetCollectionIDCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(scopeName, collectionName, opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, gocbcore.GetCollectionIDOptions, gocbcore.GetCollectionIDCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(scopeName, collectionName, opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, gocbcore.GetCollectionIDOptions, gocbcore.GetCollectionIDCallback) error); ok {
		r1 = returnFunc(scopeName, collectionName, opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_GetCollectionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionID'
type mockKvProviderCoreProvider_GetCollectionID_Call struct {
	*mock.Call
}

// GetCollectionID is a helper method to define mock.On call
//   - scopeName string
//   - collectionName string
//   - opts gocbcore.GetCollectionIDOptions
//   - cb gocbcore.GetCollectionIDCallback
func (_e *mockKvProviderCoreProvider_Expecter) GetCollectionID(scopeName interface{}, collectionName interface{}, opts interface{}, cb interface{}) *mockKvProviderCoreProvider_GetCollectionID_Call {
	return &mockKvProviderCoreProvider_GetCollectionID_Call{Call: _e.mock.On("GetCollectionID", scopeName, collectionName, opts, cb)}
}

func (_c *mockKvProviderCoreProvider_GetCollectionID_Call) Run(run func(scopeName string, collectionName string, opts gocbcore.GetCollectionIDOptions, cb gocbcore.GetCollectionIDCallback)) *mockKvProviderCoreProvider_GetCollectionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 gocbcore.GetCollectionIDOptions
		if args[2] != nil {
			arg2 = args[2].(gocbcore.GetCollectionIDOptions)
		}
		var arg3 gocbcore.GetCollectionIDCallback
		if args[3] != nil {
			arg3 = args[3].(gocbcore.GetCollectionIDCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_GetCollectionID_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_GetCollectionID_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_GetCollectionID_Call) RunAndReturn(run func(scopeName string, collectionName string, opts gocbcore.GetCollectionIDOptions, cb gocbcore.GetCollectionIDCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_GetCollectionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeta provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) GetMeta(opts gocbcore.GetMetaOptions, cb gocbcore.GetMetaCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetMetaOptions, gocbcore.GetMetaCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetMetaOptions, gocbcore.GetMetaCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.GetMetaOptions, gocbcore.GetMetaCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_GetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeta'
type mockKvProviderCoreProvider_GetMeta_Call struct {
	*mock.Call
}

// GetMeta is a helper method to define mock.On call
//   - opts gocbcore.GetMetaOptions
//   - cb gocbcore.GetMetaCallback
func (_e *mockKvProviderCoreProvider_Expecter) GetMeta(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_GetMeta_Call {
	return &mockKvProviderCoreProvider_GetMeta_Call{Call: _e.mock.On("GetMeta", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_GetMeta_Call) Run(run func(opts gocbcore.GetMetaOptions, cb gocbcore.GetMetaCallback)) *mockKvProviderCoreProvider_GetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.GetMetaOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.GetMetaOptions)
		}
		var arg1 gocbcore.GetMetaCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.GetMetaCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_GetMeta_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_GetMeta_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_GetMeta_Call) RunAndReturn(run func(opts gocbcore.GetMetaOptions, cb gocbcore.GetMetaCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_GetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetOneReplica provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) GetOneReplica(opts gocbcore.GetOneReplicaOptions, cb gocbcore.GetReplicaCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for GetOneReplica")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetOneReplicaOptions, gocbcore.GetReplicaCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.GetOneReplicaOptions, gocbcore.GetReplicaCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.GetOneReplicaOptions, gocbcore.GetReplicaCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_GetOneReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneReplica'
type mockKvProviderCoreProvider_GetOneReplica_Call struct {
	*mock.Call
}

// GetOneReplica is a helper method to define mock.On call
//   - opts gocbcore.GetOneReplicaOptions
//   - cb gocbcore.GetReplicaCallback
func (_e *mockKvProviderCoreProvider_Expecter) GetOneReplica(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_GetOneReplica_Call {
	return &mockKvProviderCoreProvider_GetOneReplica_Call{Call: _e.mock.On("GetOneReplica", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_GetOneReplica_Call) Run(run func(opts gocbcore.GetOneReplicaOptions, cb gocbcore.GetReplicaCallback)) *mockKvProviderCoreProvider_GetOneReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.GetOneReplicaOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.GetOneReplicaOptions)
		}
		var arg1 gocbcore.GetReplicaCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.GetReplicaCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_GetOneReplica_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_GetOneReplica_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_GetOneReplica_Call) RunAndReturn(run func(opts gocbcore.GetOneReplicaOptions, cb gocbcore.GetReplicaCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_GetOneReplica_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Increment(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.CounterOptions, gocbcore.CounterCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type mockKvProviderCoreProvider_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - opts gocbcore.CounterOptions
//   - cb gocbcore.CounterCallback
func (_e *mockKvProviderCoreProvider_Expecter) Increment(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Increment_Call {
	return &mockKvProviderCoreProvider_Increment_Call{Call: _e.mock.On("Increment", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Increment_Call) Run(run func(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback)) *mockKvProviderCoreProvider_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.CounterOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.CounterOptions)
		}
		var arg1 gocbcore.CounterCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.CounterCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Increment_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Increment_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Increment_Call) RunAndReturn(run func(opts gocbcore.CounterOptions, cb gocbcore.CounterCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// LookupIn provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) LookupIn(opts gocbcore.LookupInOptions, cb gocbcore.LookupInCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for LookupIn")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.LookupInOptions, gocbcore.LookupInCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.LookupInOptions, gocbcore.LookupInCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.LookupInOptions, gocbcore.LookupInCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_LookupIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupIn'
type mockKvProviderCoreProvider_LookupIn_Call struct {
	*mock.Call
}

// LookupIn is a helper method to define mock.On call
//   - opts gocbcore.LookupInOptions
//   - cb gocbcore.LookupInCallback
func (_e *mockKvProviderCoreProvider_Expecter) LookupIn(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_LookupIn_Call {
	return &mockKvProviderCoreProvider_LookupIn_Call{Call: _e.mock.On("LookupIn", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_LookupIn_Call) Run(run func(opts gocbcore.LookupInOptions, cb gocbcore.LookupInCallback)) *mockKvProviderCoreProvider_LookupIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.LookupInOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.LookupInOptions)
		}
		var arg1 gocbcore.LookupInCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.LookupInCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_LookupIn_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_LookupIn_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_LookupIn_Call) RunAndReturn(run func(opts gocbcore.LookupInOptions, cb gocbcore.LookupInCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_LookupIn_Call {
	_c.Call.Return(run)
	return _c
}

// MutateIn provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) MutateIn(opts gocbcore.MutateInOptions, cb gocbcore.MutateInCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for MutateIn")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.MutateInOptions, gocbcore.MutateInCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.MutateInOptions, gocbcore.MutateInCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.MutateInOptions, gocbcore.MutateInCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_MutateIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MutateIn'
type mockKvProviderCoreProvider_MutateIn_Call struct {
	*mock.Call
}

// MutateIn is a helper method to define mock.On call
//   - opts gocbcore.MutateInOptions
//   - cb gocbcore.MutateInCallback
func (_e *mockKvProviderCoreProvider_Expecter) MutateIn(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_MutateIn_Call {
	return &mockKvProviderCoreProvider_MutateIn_Call{Call: _e.mock.On("MutateIn", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_MutateIn_Call) Run(run func(opts gocbcore.MutateInOptions, cb gocbcore.MutateInCallback)) *mockKvProviderCoreProvider_MutateIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.MutateInOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.MutateInOptions)
		}
		var arg1 gocbcore.MutateInCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.MutateInCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_MutateIn_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_MutateIn_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_MutateIn_Call) RunAndReturn(run func(opts gocbcore.MutateInOptions, cb gocbcore.MutateInCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_MutateIn_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Observe(opts gocbcore.ObserveOptions, cb gocbcore.ObserveCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Observe")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ObserveOptions, gocbcore.ObserveCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ObserveOptions, gocbcore.ObserveCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.ObserveOptions, gocbcore.ObserveCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type mockKvProviderCoreProvider_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - opts gocbcore.ObserveOptions
//   - cb gocbcore.ObserveCallback
func (_e *mockKvProviderCoreProvider_Expecter) Observe(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Observe_Call {
	return &mockKvProviderCoreProvider_Observe_Call{Call: _e.mock.On("Observe", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Observe_Call) Run(run func(opts gocbcore.ObserveOptions, cb gocbcore.ObserveCallback)) *mockKvProviderCoreProvider_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.ObserveOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.ObserveOptions)
		}
		var arg1 gocbcore.ObserveCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.ObserveCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Observe_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Observe_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Observe_Call) RunAndReturn(run func(opts gocbcore.ObserveOptions, cb gocbcore.ObserveCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Observe_Call {
	_c.Call.Return(run)
	return _c
}

// ObserveVb provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) ObserveVb(opts gocbcore.ObserveVbOptions, cb gocbcore.ObserveVbCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for ObserveVb")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ObserveVbOptions, gocbcore.ObserveVbCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ObserveVbOptions, gocbcore.ObserveVbCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.ObserveVbOptions, gocbcore.ObserveVbCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_ObserveVb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObserveVb'
type mockKvProviderCoreProvider_ObserveVb_Call struct {
	*mock.Call
}

// ObserveVb is a helper method to define mock.On call
//   - opts gocbcore.ObserveVbOptions
//   - cb gocbcore.ObserveVbCallback
func (_e *mockKvProviderCoreProvider_Expecter) ObserveVb(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_ObserveVb_Call {
	return &mockKvProviderCoreProvider_ObserveVb_Call{Call: _e.mock.On("ObserveVb", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_ObserveVb_Call) Run(run func(opts gocbcore.ObserveVbOptions, cb gocbcore.ObserveVbCallback)) *mockKvProviderCoreProvider_ObserveVb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.ObserveVbOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.ObserveVbOptions)
		}
		var arg1 gocbcore.ObserveVbCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.ObserveVbCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_ObserveVb_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_ObserveVb_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_ObserveVb_Call) RunAndReturn(run func(opts gocbcore.ObserveVbOptions, cb gocbcore.ObserveVbCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_ObserveVb_Call {
	_c.Call.Return(run)
	return _c
}

// Prepend provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Prepend(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Prepend")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.AdjoinOptions, gocbcore.AdjoinCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Prepend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepend'
type mockKvProviderCoreProvider_Prepend_Call struct {
	*mock.Call
}

// Prepend is a helper method to define mock.On call
//   - opts gocbcore.AdjoinOptions
//   - cb gocbcore.AdjoinCallback
func (_e *mockKvProviderCoreProvider_Expecter) Prepend(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Prepend_Call {
	return &mockKvProviderCoreProvider_Prepend_Call{Call: _e.mock.On("Prepend", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Prepend_Call) Run(run func(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback)) *mockKvProviderCoreProvider_Prepend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.AdjoinOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.AdjoinOptions)
		}
		var arg1 gocbcore.AdjoinCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.AdjoinCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Prepend_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Prepend_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Prepend_Call) RunAndReturn(run func(opts gocbcore.AdjoinOptions, cb gocbcore.AdjoinCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Prepend_Call {
	_c.Call.Return(run)
	return _c
}

// RangeScanCreate provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) RangeScanCreate(vbID uint16, opts gocbcore.RangeScanCreateOptions, cb gocbcore.RangeScanCreateCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(vbID, opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for RangeScanCreate")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint16, gocbcore.RangeScanCreateOptions, gocbcore.RangeScanCreateCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(vbID, opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(uint16, gocbcore.RangeScanCreateOptions, gocbcore.RangeScanCreateCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(vbID, opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint16, gocbcore.RangeScanCreateOptions, gocbcore.RangeScanCreateCallback) error); ok {
		r1 = returnFunc(vbID, opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_RangeScanCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RangeScanCreate'
type mockKvProviderCoreProvider_RangeScanCreate_Call struct {
	*mock.Call
}

// RangeScanCreate is a helper method to define mock.On call
//   - vbID uint16
//   - opts gocbcore.RangeScanCreateOptions
//   - cb gocbcore.RangeScanCreateCallback
func (_e *mockKvProviderCoreProvider_Expecter) RangeScanCreate(vbID interface{}, opts interface{}, cb interface{}) *mockKvProviderCoreProvider_RangeScanCreate_Call {
	return &mockKvProviderCoreProvider_RangeScanCreate_Call{Call: _e.mock.On("RangeScanCreate", vbID, opts, cb)}
}

func (_c *mockKvProviderCoreProvider_RangeScanCreate_Call) Run(run func(vbID uint16, opts gocbcore.RangeScanCreateOptions, cb gocbcore.RangeScanCreateCallback)) *mockKvProviderCoreProvider_RangeScanCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint16
		if args[0] != nil {
			arg0 = args[0].(uint16)
		}
		var arg1 gocbcore.RangeScanCreateOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.RangeScanCreateOptions)
		}
		var arg2 gocbcore.RangeScanCreateCallback
		if args[2] != nil {
			arg2 = args[2].(gocbcore.RangeScanCreateCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_RangeScanCreate_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_RangeScanCreate_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_RangeScanCreate_Call) RunAndReturn(run func(vbID uint16, opts gocbcore.RangeScanCreateOptions, cb gocbcore.RangeScanCreateCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_RangeScanCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Replace(opts gocbcore.ReplaceOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ReplaceOptions, gocbcore.StoreCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.ReplaceOptions, gocbcore.StoreCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.ReplaceOptions, gocbcore.StoreCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type mockKvProviderCoreProvider_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - opts gocbcore.ReplaceOptions
//   - cb gocbcore.StoreCallback
func (_e *mockKvProviderCoreProvider_Expecter) Replace(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Replace_Call {
	return &mockKvProviderCoreProvider_Replace_Call{Call: _e.mock.On("Replace", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Replace_Call) Run(run func(opts gocbcore.ReplaceOptions, cb gocbcore.StoreCallback)) *mockKvProviderCoreProvider_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.ReplaceOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.ReplaceOptions)
		}
		var arg1 gocbcore.StoreCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.StoreCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Replace_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Replace_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Replace_Call) RunAndReturn(run func(opts gocbcore.ReplaceOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Set(opts gocbcore.SetOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.SetOptions, gocbcore.StoreCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.SetOptions, gocbcore.StoreCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.SetOptions, gocbcore.StoreCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type mockKvProviderCoreProvider_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - opts gocbcore.SetOptions
//   - cb gocbcore.StoreCallback
func (_e *mockKvProviderCoreProvider_Expecter) Set(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Set_Call {
	return &mockKvProviderCoreProvider_Set_Call{Call: _e.mock.On("Set", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Set_Call) Run(run func(opts gocbcore.SetOptions, cb gocbcore.StoreCallback)) *mockKvProviderCoreProvider_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.SetOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.SetOptions)
		}
		var arg1 gocbcore.StoreCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.StoreCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Set_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Set_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Set_Call) RunAndReturn(run func(opts gocbcore.SetOptions, cb gocbcore.StoreCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Touch(opts gocbcore.TouchOptions, cb gocbcore.TouchCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.TouchOptions, gocbcore.TouchCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.TouchOptions, gocbcore.TouchCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.TouchOptions, gocbcore.TouchCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type mockKvProviderCoreProvider_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - opts gocbcore.TouchOptions
//   - cb gocbcore.TouchCallback
func (_e *mockKvProviderCoreProvider_Expecter) Touch(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Touch_Call {
	return &mockKvProviderCoreProvider_Touch_Call{Call: _e.mock.On("Touch", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Touch_Call) Run(run func(opts gocbcore.TouchOptions, cb gocbcore.TouchCallback)) *mockKvProviderCoreProvider_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.TouchOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.TouchOptions)
		}
		var arg1 gocbcore.TouchCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.TouchCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Touch_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Touch_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Touch_Call) RunAndReturn(run func(opts gocbcore.TouchOptions, cb gocbcore.TouchCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) Unlock(opts gocbcore.UnlockOptions, cb gocbcore.UnlockCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.UnlockOptions, gocbcore.UnlockCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.UnlockOptions, gocbcore.UnlockCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.UnlockOptions, gocbcore.UnlockCallback) error); ok {
		r1 = returnFunc(opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type mockKvProviderCoreProvider_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - opts gocbcore.UnlockOptions
//   - cb gocbcore.UnlockCallback
func (_e *mockKvProviderCoreProvider_Expecter) Unlock(opts interface{}, cb interface{}) *mockKvProviderCoreProvider_Unlock_Call {
	return &mockKvProviderCoreProvider_Unlock_Call{Call: _e.mock.On("Unlock", opts, cb)}
}

func (_c *mockKvProviderCoreProvider_Unlock_Call) Run(run func(opts gocbcore.UnlockOptions, cb gocbcore.UnlockCallback)) *mockKvProviderCoreProvider_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.UnlockOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.UnlockOptions)
		}
		var arg1 gocbcore.UnlockCallback
		if args[1] != nil {
			arg1 = args[1].(gocbcore.UnlockCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_Unlock_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_Unlock_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_Unlock_Call) RunAndReturn(run func(opts gocbcore.UnlockOptions, cb gocbcore.UnlockCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForConfigSnapshot provides a mock function for the type mockKvProviderCoreProvider
func (_mock *mockKvProviderCoreProvider) WaitForConfigSnapshot(deadline time.Time, opts gocbcore.WaitForConfigSnapshotOptions, cb gocbcore.WaitForConfigSnapshotCallback) (gocbcore.PendingOp, error) {
	ret := _mock.Called(deadline, opts, cb)

	if len(ret) == 0 {
		panic("no return value specified for WaitForConfigSnapshot")
	}

	var r0 gocbcore.PendingOp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time, gocbcore.WaitForConfigSnapshotOptions, gocbcore.WaitForConfigSnapshotCallback) (gocbcore.PendingOp, error)); ok {
		return returnFunc(deadline, opts, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time, gocbcore.WaitForConfigSnapshotOptions, gocbcore.WaitForConfigSnapshotCallback) gocbcore.PendingOp); ok {
		r0 = returnFunc(deadline, opts, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gocbcore.PendingOp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time, gocbcore.WaitForConfigSnapshotOptions, gocbcore.WaitForConfigSnapshotCallback) error); ok {
		r1 = returnFunc(deadline, opts, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProviderCoreProvider_WaitForConfigSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForConfigSnapshot'
type mockKvProviderCoreProvider_WaitForConfigSnapshot_Call struct {
	*mock.Call
}

// WaitForConfigSnapshot is a helper method to define mock.On call
//   - deadline time.Time
//   - opts gocbcore.WaitForConfigSnapshotOptions
//   - cb gocbcore.WaitForConfigSnapshotCallback
func (_e *mockKvProviderCoreProvider_Expecter) WaitForConfigSnapshot(deadline interface{}, opts interface{}, cb interface{}) *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call {
	return &mockKvProviderCoreProvider_WaitForConfigSnapshot_Call{Call: _e.mock.On("WaitForConfigSnapshot", deadline, opts, cb)}
}

func (_c *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call) Run(run func(deadline time.Time, opts gocbcore.WaitForConfigSnapshotOptions, cb gocbcore.WaitForConfigSnapshotCallback)) *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		var arg1 gocbcore.WaitForConfigSnapshotOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.WaitForConfigSnapshotOptions)
		}
		var arg2 gocbcore.WaitForConfigSnapshotCallback
		if args[2] != nil {
			arg2 = args[2].(gocbcore.WaitForConfigSnapshotCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call) Return(pendingOp gocbcore.PendingOp, err error) *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call {
	_c.Call.Return(pendingOp, err)
	return _c
}

func (_c *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call) RunAndReturn(run func(deadline time.Time, opts gocbcore.WaitForConfigSnapshotOptions, cb gocbcore.WaitForConfigSnapshotCallback) (gocbcore.PendingOp, error)) *mockKvProviderCoreProvider_WaitForConfigSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
