// Code generated by mockery v1.0.0. DO NOT EDIT.

package gocb

import (
	gocbcore "github.com/couchbase/gocbcore/v9"
	mock "github.com/stretchr/testify/mock"
)

// mockViewProvider is an autogenerated mock type for the viewProvider type
type mockViewProvider struct {
	mock.Mock
}

// ViewQuery provides a mock function with given fields: opts
func (_m *mockViewProvider) ViewQuery(opts gocbcore.ViewQueryOptions) (viewRowReader, error) {
	ret := _m.Called(opts)

	var r0 viewRowReader
	if rf, ok := ret.Get(0).(func(gocbcore.ViewQueryOptions) viewRowReader); ok {
		r0 = rf(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(viewRowReader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(gocbcore.ViewQueryOptions) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
