// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockKvProvider creates a new instance of mockKvProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockKvProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockKvProvider {
	mock := &mockKvProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockKvProvider is an autogenerated mock type for the kvProvider type
type mockKvProvider struct {
	mock.Mock
}

type mockKvProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockKvProvider) EXPECT() *mockKvProvider_Expecter {
	return &mockKvProvider_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Append(collection *Collection, s string, bytes []byte, appendOptions *AppendOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, bytes, appendOptions)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []byte, *AppendOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, bytes, appendOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []byte, *AppendOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, bytes, appendOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []byte, *AppendOptions) error); ok {
		r1 = returnFunc(collection, s, bytes, appendOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type mockKvProvider_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - bytes []byte
//   - appendOptions *AppendOptions
func (_e *mockKvProvider_Expecter) Append(collection interface{}, s interface{}, bytes interface{}, appendOptions interface{}) *mockKvProvider_Append_Call {
	return &mockKvProvider_Append_Call{Call: _e.mock.On("Append", collection, s, bytes, appendOptions)}
}

func (_c *mockKvProvider_Append_Call) Run(run func(collection *Collection, s string, bytes []byte, appendOptions *AppendOptions)) *mockKvProvider_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 *AppendOptions
		if args[3] != nil {
			arg3 = args[3].(*AppendOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Append_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Append_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Append_Call) RunAndReturn(run func(collection *Collection, s string, bytes []byte, appendOptions *AppendOptions) (*MutationResult, error)) *mockKvProvider_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Decrement provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Decrement(collection *Collection, s string, decrementOptions *DecrementOptions) (*CounterResult, error) {
	ret := _mock.Called(collection, s, decrementOptions)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 *CounterResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *DecrementOptions) (*CounterResult, error)); ok {
		return returnFunc(collection, s, decrementOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *DecrementOptions) *CounterResult); ok {
		r0 = returnFunc(collection, s, decrementOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CounterResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *DecrementOptions) error); ok {
		r1 = returnFunc(collection, s, decrementOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type mockKvProvider_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - decrementOptions *DecrementOptions
func (_e *mockKvProvider_Expecter) Decrement(collection interface{}, s interface{}, decrementOptions interface{}) *mockKvProvider_Decrement_Call {
	return &mockKvProvider_Decrement_Call{Call: _e.mock.On("Decrement", collection, s, decrementOptions)}
}

func (_c *mockKvProvider_Decrement_Call) Run(run func(collection *Collection, s string, decrementOptions *DecrementOptions)) *mockKvProvider_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *DecrementOptions
		if args[2] != nil {
			arg2 = args[2].(*DecrementOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Decrement_Call) Return(counterResult *CounterResult, err error) *mockKvProvider_Decrement_Call {
	_c.Call.Return(counterResult, err)
	return _c
}

func (_c *mockKvProvider_Decrement_Call) RunAndReturn(run func(collection *Collection, s string, decrementOptions *DecrementOptions) (*CounterResult, error)) *mockKvProvider_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Exists(collection *Collection, s string, existsOptions *ExistsOptions) (*ExistsResult, error) {
	ret := _mock.Called(collection, s, existsOptions)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 *ExistsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *ExistsOptions) (*ExistsResult, error)); ok {
		return returnFunc(collection, s, existsOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *ExistsOptions) *ExistsResult); ok {
		r0 = returnFunc(collection, s, existsOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExistsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *ExistsOptions) error); ok {
		r1 = returnFunc(collection, s, existsOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type mockKvProvider_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - existsOptions *ExistsOptions
func (_e *mockKvProvider_Expecter) Exists(collection interface{}, s interface{}, existsOptions interface{}) *mockKvProvider_Exists_Call {
	return &mockKvProvider_Exists_Call{Call: _e.mock.On("Exists", collection, s, existsOptions)}
}

func (_c *mockKvProvider_Exists_Call) Run(run func(collection *Collection, s string, existsOptions *ExistsOptions)) *mockKvProvider_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ExistsOptions
		if args[2] != nil {
			arg2 = args[2].(*ExistsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Exists_Call) Return(existsResult *ExistsResult, err error) *mockKvProvider_Exists_Call {
	_c.Call.Return(existsResult, err)
	return _c
}

func (_c *mockKvProvider_Exists_Call) RunAndReturn(run func(collection *Collection, s string, existsOptions *ExistsOptions) (*ExistsResult, error)) *mockKvProvider_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Get(collection *Collection, s string, getOptions *GetOptions) (*GetResult, error) {
	ret := _mock.Called(collection, s, getOptions)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *GetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetOptions) (*GetResult, error)); ok {
		return returnFunc(collection, s, getOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetOptions) *GetResult); ok {
		r0 = returnFunc(collection, s, getOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *GetOptions) error); ok {
		r1 = returnFunc(collection, s, getOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockKvProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - getOptions *GetOptions
func (_e *mockKvProvider_Expecter) Get(collection interface{}, s interface{}, getOptions interface{}) *mockKvProvider_Get_Call {
	return &mockKvProvider_Get_Call{Call: _e.mock.On("Get", collection, s, getOptions)}
}

func (_c *mockKvProvider_Get_Call) Run(run func(collection *Collection, s string, getOptions *GetOptions)) *mockKvProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *GetOptions
		if args[2] != nil {
			arg2 = args[2].(*GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Get_Call) Return(getResult *GetResult, err error) *mockKvProvider_Get_Call {
	_c.Call.Return(getResult, err)
	return _c
}

func (_c *mockKvProvider_Get_Call) RunAndReturn(run func(collection *Collection, s string, getOptions *GetOptions) (*GetResult, error)) *mockKvProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllReplicas provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) GetAllReplicas(collection *Collection, s string, getAllReplicaOptions *GetAllReplicaOptions) (*GetAllReplicasResult, error) {
	ret := _mock.Called(collection, s, getAllReplicaOptions)

	if len(ret) == 0 {
		panic("no return value specified for GetAllReplicas")
	}

	var r0 *GetAllReplicasResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetAllReplicaOptions) (*GetAllReplicasResult, error)); ok {
		return returnFunc(collection, s, getAllReplicaOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetAllReplicaOptions) *GetAllReplicasResult); ok {
		r0 = returnFunc(collection, s, getAllReplicaOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetAllReplicasResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *GetAllReplicaOptions) error); ok {
		r1 = returnFunc(collection, s, getAllReplicaOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_GetAllReplicas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllReplicas'
type mockKvProvider_GetAllReplicas_Call struct {
	*mock.Call
}

// GetAllReplicas is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - getAllReplicaOptions *GetAllReplicaOptions
func (_e *mockKvProvider_Expecter) GetAllReplicas(collection interface{}, s interface{}, getAllReplicaOptions interface{}) *mockKvProvider_GetAllReplicas_Call {
	return &mockKvProvider_GetAllReplicas_Call{Call: _e.mock.On("GetAllReplicas", collection, s, getAllReplicaOptions)}
}

func (_c *mockKvProvider_GetAllReplicas_Call) Run(run func(collection *Collection, s string, getAllReplicaOptions *GetAllReplicaOptions)) *mockKvProvider_GetAllReplicas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *GetAllReplicaOptions
		if args[2] != nil {
			arg2 = args[2].(*GetAllReplicaOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_GetAllReplicas_Call) Return(getAllReplicasResult *GetAllReplicasResult, err error) *mockKvProvider_GetAllReplicas_Call {
	_c.Call.Return(getAllReplicasResult, err)
	return _c
}

func (_c *mockKvProvider_GetAllReplicas_Call) RunAndReturn(run func(collection *Collection, s string, getAllReplicaOptions *GetAllReplicaOptions) (*GetAllReplicasResult, error)) *mockKvProvider_GetAllReplicas_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndLock provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) GetAndLock(collection *Collection, s string, duration time.Duration, getAndLockOptions *GetAndLockOptions) (*GetResult, error) {
	ret := _mock.Called(collection, s, duration, getAndLockOptions)

	if len(ret) == 0 {
		panic("no return value specified for GetAndLock")
	}

	var r0 *GetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *GetAndLockOptions) (*GetResult, error)); ok {
		return returnFunc(collection, s, duration, getAndLockOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *GetAndLockOptions) *GetResult); ok {
		r0 = returnFunc(collection, s, duration, getAndLockOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, time.Duration, *GetAndLockOptions) error); ok {
		r1 = returnFunc(collection, s, duration, getAndLockOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_GetAndLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndLock'
type mockKvProvider_GetAndLock_Call struct {
	*mock.Call
}

// GetAndLock is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - duration time.Duration
//   - getAndLockOptions *GetAndLockOptions
func (_e *mockKvProvider_Expecter) GetAndLock(collection interface{}, s interface{}, duration interface{}, getAndLockOptions interface{}) *mockKvProvider_GetAndLock_Call {
	return &mockKvProvider_GetAndLock_Call{Call: _e.mock.On("GetAndLock", collection, s, duration, getAndLockOptions)}
}

func (_c *mockKvProvider_GetAndLock_Call) Run(run func(collection *Collection, s string, duration time.Duration, getAndLockOptions *GetAndLockOptions)) *mockKvProvider_GetAndLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 *GetAndLockOptions
		if args[3] != nil {
			arg3 = args[3].(*GetAndLockOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_GetAndLock_Call) Return(getResult *GetResult, err error) *mockKvProvider_GetAndLock_Call {
	_c.Call.Return(getResult, err)
	return _c
}

func (_c *mockKvProvider_GetAndLock_Call) RunAndReturn(run func(collection *Collection, s string, duration time.Duration, getAndLockOptions *GetAndLockOptions) (*GetResult, error)) *mockKvProvider_GetAndLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndTouch provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) GetAndTouch(collection *Collection, s string, duration time.Duration, getAndTouchOptions *GetAndTouchOptions) (*GetResult, error) {
	ret := _mock.Called(collection, s, duration, getAndTouchOptions)

	if len(ret) == 0 {
		panic("no return value specified for GetAndTouch")
	}

	var r0 *GetResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *GetAndTouchOptions) (*GetResult, error)); ok {
		return returnFunc(collection, s, duration, getAndTouchOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *GetAndTouchOptions) *GetResult); ok {
		r0 = returnFunc(collection, s, duration, getAndTouchOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, time.Duration, *GetAndTouchOptions) error); ok {
		r1 = returnFunc(collection, s, duration, getAndTouchOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_GetAndTouch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndTouch'
type mockKvProvider_GetAndTouch_Call struct {
	*mock.Call
}

// GetAndTouch is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - duration time.Duration
//   - getAndTouchOptions *GetAndTouchOptions
func (_e *mockKvProvider_Expecter) GetAndTouch(collection interface{}, s interface{}, duration interface{}, getAndTouchOptions interface{}) *mockKvProvider_GetAndTouch_Call {
	return &mockKvProvider_GetAndTouch_Call{Call: _e.mock.On("GetAndTouch", collection, s, duration, getAndTouchOptions)}
}

func (_c *mockKvProvider_GetAndTouch_Call) Run(run func(collection *Collection, s string, duration time.Duration, getAndTouchOptions *GetAndTouchOptions)) *mockKvProvider_GetAndTouch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 *GetAndTouchOptions
		if args[3] != nil {
			arg3 = args[3].(*GetAndTouchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_GetAndTouch_Call) Return(getResult *GetResult, err error) *mockKvProvider_GetAndTouch_Call {
	_c.Call.Return(getResult, err)
	return _c
}

func (_c *mockKvProvider_GetAndTouch_Call) RunAndReturn(run func(collection *Collection, s string, duration time.Duration, getAndTouchOptions *GetAndTouchOptions) (*GetResult, error)) *mockKvProvider_GetAndTouch_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnyReplica provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) GetAnyReplica(c *Collection, id string, opts *GetAnyReplicaOptions) (*GetReplicaResult, error) {
	ret := _mock.Called(c, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetAnyReplica")
	}

	var r0 *GetReplicaResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetAnyReplicaOptions) (*GetReplicaResult, error)); ok {
		return returnFunc(c, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *GetAnyReplicaOptions) *GetReplicaResult); ok {
		r0 = returnFunc(c, id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetReplicaResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *GetAnyReplicaOptions) error); ok {
		r1 = returnFunc(c, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_GetAnyReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnyReplica'
type mockKvProvider_GetAnyReplica_Call struct {
	*mock.Call
}

// GetAnyReplica is a helper method to define mock.On call
//   - c *Collection
//   - id string
//   - opts *GetAnyReplicaOptions
func (_e *mockKvProvider_Expecter) GetAnyReplica(c interface{}, id interface{}, opts interface{}) *mockKvProvider_GetAnyReplica_Call {
	return &mockKvProvider_GetAnyReplica_Call{Call: _e.mock.On("GetAnyReplica", c, id, opts)}
}

func (_c *mockKvProvider_GetAnyReplica_Call) Run(run func(c *Collection, id string, opts *GetAnyReplicaOptions)) *mockKvProvider_GetAnyReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *GetAnyReplicaOptions
		if args[2] != nil {
			arg2 = args[2].(*GetAnyReplicaOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_GetAnyReplica_Call) Return(getReplicaResult *GetReplicaResult, err error) *mockKvProvider_GetAnyReplica_Call {
	_c.Call.Return(getReplicaResult, err)
	return _c
}

func (_c *mockKvProvider_GetAnyReplica_Call) RunAndReturn(run func(c *Collection, id string, opts *GetAnyReplicaOptions) (*GetReplicaResult, error)) *mockKvProvider_GetAnyReplica_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Increment(collection *Collection, s string, incrementOptions *IncrementOptions) (*CounterResult, error) {
	ret := _mock.Called(collection, s, incrementOptions)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 *CounterResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *IncrementOptions) (*CounterResult, error)); ok {
		return returnFunc(collection, s, incrementOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *IncrementOptions) *CounterResult); ok {
		r0 = returnFunc(collection, s, incrementOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CounterResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *IncrementOptions) error); ok {
		r1 = returnFunc(collection, s, incrementOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type mockKvProvider_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - incrementOptions *IncrementOptions
func (_e *mockKvProvider_Expecter) Increment(collection interface{}, s interface{}, incrementOptions interface{}) *mockKvProvider_Increment_Call {
	return &mockKvProvider_Increment_Call{Call: _e.mock.On("Increment", collection, s, incrementOptions)}
}

func (_c *mockKvProvider_Increment_Call) Run(run func(collection *Collection, s string, incrementOptions *IncrementOptions)) *mockKvProvider_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *IncrementOptions
		if args[2] != nil {
			arg2 = args[2].(*IncrementOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Increment_Call) Return(counterResult *CounterResult, err error) *mockKvProvider_Increment_Call {
	_c.Call.Return(counterResult, err)
	return _c
}

func (_c *mockKvProvider_Increment_Call) RunAndReturn(run func(collection *Collection, s string, incrementOptions *IncrementOptions) (*CounterResult, error)) *mockKvProvider_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Insert(collection *Collection, s string, ifaceVal interface{}, insertOptions *InsertOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, ifaceVal, insertOptions)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *InsertOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, ifaceVal, insertOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *InsertOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, ifaceVal, insertOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, interface{}, *InsertOptions) error); ok {
		r1 = returnFunc(collection, s, ifaceVal, insertOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type mockKvProvider_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - ifaceVal interface{}
//   - insertOptions *InsertOptions
func (_e *mockKvProvider_Expecter) Insert(collection interface{}, s interface{}, ifaceVal interface{}, insertOptions interface{}) *mockKvProvider_Insert_Call {
	return &mockKvProvider_Insert_Call{Call: _e.mock.On("Insert", collection, s, ifaceVal, insertOptions)}
}

func (_c *mockKvProvider_Insert_Call) Run(run func(collection *Collection, s string, ifaceVal interface{}, insertOptions *InsertOptions)) *mockKvProvider_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *InsertOptions
		if args[3] != nil {
			arg3 = args[3].(*InsertOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Insert_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Insert_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Insert_Call) RunAndReturn(run func(collection *Collection, s string, ifaceVal interface{}, insertOptions *InsertOptions) (*MutationResult, error)) *mockKvProvider_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// LookupIn provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) LookupIn(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInOptions *LookupInOptions) (*LookupInResult, error) {
	ret := _mock.Called(collection, s, lookupInSpecs, lookupInOptions)

	if len(ret) == 0 {
		panic("no return value specified for LookupIn")
	}

	var r0 *LookupInResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInOptions) (*LookupInResult, error)); ok {
		return returnFunc(collection, s, lookupInSpecs, lookupInOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInOptions) *LookupInResult); ok {
		r0 = returnFunc(collection, s, lookupInSpecs, lookupInOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LookupInResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []LookupInSpec, *LookupInOptions) error); ok {
		r1 = returnFunc(collection, s, lookupInSpecs, lookupInOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_LookupIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupIn'
type mockKvProvider_LookupIn_Call struct {
	*mock.Call
}

// LookupIn is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - lookupInSpecs []LookupInSpec
//   - lookupInOptions *LookupInOptions
func (_e *mockKvProvider_Expecter) LookupIn(collection interface{}, s interface{}, lookupInSpecs interface{}, lookupInOptions interface{}) *mockKvProvider_LookupIn_Call {
	return &mockKvProvider_LookupIn_Call{Call: _e.mock.On("LookupIn", collection, s, lookupInSpecs, lookupInOptions)}
}

func (_c *mockKvProvider_LookupIn_Call) Run(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInOptions *LookupInOptions)) *mockKvProvider_LookupIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []LookupInSpec
		if args[2] != nil {
			arg2 = args[2].([]LookupInSpec)
		}
		var arg3 *LookupInOptions
		if args[3] != nil {
			arg3 = args[3].(*LookupInOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_LookupIn_Call) Return(lookupInResult *LookupInResult, err error) *mockKvProvider_LookupIn_Call {
	_c.Call.Return(lookupInResult, err)
	return _c
}

func (_c *mockKvProvider_LookupIn_Call) RunAndReturn(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInOptions *LookupInOptions) (*LookupInResult, error)) *mockKvProvider_LookupIn_Call {
	_c.Call.Return(run)
	return _c
}

// LookupInAllReplicas provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) LookupInAllReplicas(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAllReplicaOptions *LookupInAllReplicaOptions) (*LookupInAllReplicasResult, error) {
	ret := _mock.Called(collection, s, lookupInSpecs, lookupInAllReplicaOptions)

	if len(ret) == 0 {
		panic("no return value specified for LookupInAllReplicas")
	}

	var r0 *LookupInAllReplicasResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInAllReplicaOptions) (*LookupInAllReplicasResult, error)); ok {
		return returnFunc(collection, s, lookupInSpecs, lookupInAllReplicaOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInAllReplicaOptions) *LookupInAllReplicasResult); ok {
		r0 = returnFunc(collection, s, lookupInSpecs, lookupInAllReplicaOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LookupInAllReplicasResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []LookupInSpec, *LookupInAllReplicaOptions) error); ok {
		r1 = returnFunc(collection, s, lookupInSpecs, lookupInAllReplicaOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_LookupInAllReplicas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupInAllReplicas'
type mockKvProvider_LookupInAllReplicas_Call struct {
	*mock.Call
}

// LookupInAllReplicas is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - lookupInSpecs []LookupInSpec
//   - lookupInAllReplicaOptions *LookupInAllReplicaOptions
func (_e *mockKvProvider_Expecter) LookupInAllReplicas(collection interface{}, s interface{}, lookupInSpecs interface{}, lookupInAllReplicaOptions interface{}) *mockKvProvider_LookupInAllReplicas_Call {
	return &mockKvProvider_LookupInAllReplicas_Call{Call: _e.mock.On("LookupInAllReplicas", collection, s, lookupInSpecs, lookupInAllReplicaOptions)}
}

func (_c *mockKvProvider_LookupInAllReplicas_Call) Run(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAllReplicaOptions *LookupInAllReplicaOptions)) *mockKvProvider_LookupInAllReplicas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []LookupInSpec
		if args[2] != nil {
			arg2 = args[2].([]LookupInSpec)
		}
		var arg3 *LookupInAllReplicaOptions
		if args[3] != nil {
			arg3 = args[3].(*LookupInAllReplicaOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_LookupInAllReplicas_Call) Return(lookupInAllReplicasResult *LookupInAllReplicasResult, err error) *mockKvProvider_LookupInAllReplicas_Call {
	_c.Call.Return(lookupInAllReplicasResult, err)
	return _c
}

func (_c *mockKvProvider_LookupInAllReplicas_Call) RunAndReturn(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAllReplicaOptions *LookupInAllReplicaOptions) (*LookupInAllReplicasResult, error)) *mockKvProvider_LookupInAllReplicas_Call {
	_c.Call.Return(run)
	return _c
}

// LookupInAnyReplica provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) LookupInAnyReplica(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAnyReplicaOptions *LookupInAnyReplicaOptions) (*LookupInReplicaResult, error) {
	ret := _mock.Called(collection, s, lookupInSpecs, lookupInAnyReplicaOptions)

	if len(ret) == 0 {
		panic("no return value specified for LookupInAnyReplica")
	}

	var r0 *LookupInReplicaResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInAnyReplicaOptions) (*LookupInReplicaResult, error)); ok {
		return returnFunc(collection, s, lookupInSpecs, lookupInAnyReplicaOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []LookupInSpec, *LookupInAnyReplicaOptions) *LookupInReplicaResult); ok {
		r0 = returnFunc(collection, s, lookupInSpecs, lookupInAnyReplicaOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*LookupInReplicaResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []LookupInSpec, *LookupInAnyReplicaOptions) error); ok {
		r1 = returnFunc(collection, s, lookupInSpecs, lookupInAnyReplicaOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_LookupInAnyReplica_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupInAnyReplica'
type mockKvProvider_LookupInAnyReplica_Call struct {
	*mock.Call
}

// LookupInAnyReplica is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - lookupInSpecs []LookupInSpec
//   - lookupInAnyReplicaOptions *LookupInAnyReplicaOptions
func (_e *mockKvProvider_Expecter) LookupInAnyReplica(collection interface{}, s interface{}, lookupInSpecs interface{}, lookupInAnyReplicaOptions interface{}) *mockKvProvider_LookupInAnyReplica_Call {
	return &mockKvProvider_LookupInAnyReplica_Call{Call: _e.mock.On("LookupInAnyReplica", collection, s, lookupInSpecs, lookupInAnyReplicaOptions)}
}

func (_c *mockKvProvider_LookupInAnyReplica_Call) Run(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAnyReplicaOptions *LookupInAnyReplicaOptions)) *mockKvProvider_LookupInAnyReplica_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []LookupInSpec
		if args[2] != nil {
			arg2 = args[2].([]LookupInSpec)
		}
		var arg3 *LookupInAnyReplicaOptions
		if args[3] != nil {
			arg3 = args[3].(*LookupInAnyReplicaOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_LookupInAnyReplica_Call) Return(lookupInReplicaResult *LookupInReplicaResult, err error) *mockKvProvider_LookupInAnyReplica_Call {
	_c.Call.Return(lookupInReplicaResult, err)
	return _c
}

func (_c *mockKvProvider_LookupInAnyReplica_Call) RunAndReturn(run func(collection *Collection, s string, lookupInSpecs []LookupInSpec, lookupInAnyReplicaOptions *LookupInAnyReplicaOptions) (*LookupInReplicaResult, error)) *mockKvProvider_LookupInAnyReplica_Call {
	_c.Call.Return(run)
	return _c
}

// MutateIn provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) MutateIn(collection *Collection, s string, mutateInSpecs []MutateInSpec, mutateInOptions *MutateInOptions) (*MutateInResult, error) {
	ret := _mock.Called(collection, s, mutateInSpecs, mutateInOptions)

	if len(ret) == 0 {
		panic("no return value specified for MutateIn")
	}

	var r0 *MutateInResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []MutateInSpec, *MutateInOptions) (*MutateInResult, error)); ok {
		return returnFunc(collection, s, mutateInSpecs, mutateInOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []MutateInSpec, *MutateInOptions) *MutateInResult); ok {
		r0 = returnFunc(collection, s, mutateInSpecs, mutateInOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutateInResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []MutateInSpec, *MutateInOptions) error); ok {
		r1 = returnFunc(collection, s, mutateInSpecs, mutateInOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_MutateIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MutateIn'
type mockKvProvider_MutateIn_Call struct {
	*mock.Call
}

// MutateIn is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - mutateInSpecs []MutateInSpec
//   - mutateInOptions *MutateInOptions
func (_e *mockKvProvider_Expecter) MutateIn(collection interface{}, s interface{}, mutateInSpecs interface{}, mutateInOptions interface{}) *mockKvProvider_MutateIn_Call {
	return &mockKvProvider_MutateIn_Call{Call: _e.mock.On("MutateIn", collection, s, mutateInSpecs, mutateInOptions)}
}

func (_c *mockKvProvider_MutateIn_Call) Run(run func(collection *Collection, s string, mutateInSpecs []MutateInSpec, mutateInOptions *MutateInOptions)) *mockKvProvider_MutateIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []MutateInSpec
		if args[2] != nil {
			arg2 = args[2].([]MutateInSpec)
		}
		var arg3 *MutateInOptions
		if args[3] != nil {
			arg3 = args[3].(*MutateInOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_MutateIn_Call) Return(mutateInResult *MutateInResult, err error) *mockKvProvider_MutateIn_Call {
	_c.Call.Return(mutateInResult, err)
	return _c
}

func (_c *mockKvProvider_MutateIn_Call) RunAndReturn(run func(collection *Collection, s string, mutateInSpecs []MutateInSpec, mutateInOptions *MutateInOptions) (*MutateInResult, error)) *mockKvProvider_MutateIn_Call {
	_c.Call.Return(run)
	return _c
}

// Prepend provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Prepend(collection *Collection, s string, bytes []byte, prependOptions *PrependOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, bytes, prependOptions)

	if len(ret) == 0 {
		panic("no return value specified for Prepend")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []byte, *PrependOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, bytes, prependOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, []byte, *PrependOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, bytes, prependOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, []byte, *PrependOptions) error); ok {
		r1 = returnFunc(collection, s, bytes, prependOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Prepend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepend'
type mockKvProvider_Prepend_Call struct {
	*mock.Call
}

// Prepend is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - bytes []byte
//   - prependOptions *PrependOptions
func (_e *mockKvProvider_Expecter) Prepend(collection interface{}, s interface{}, bytes interface{}, prependOptions interface{}) *mockKvProvider_Prepend_Call {
	return &mockKvProvider_Prepend_Call{Call: _e.mock.On("Prepend", collection, s, bytes, prependOptions)}
}

func (_c *mockKvProvider_Prepend_Call) Run(run func(collection *Collection, s string, bytes []byte, prependOptions *PrependOptions)) *mockKvProvider_Prepend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 *PrependOptions
		if args[3] != nil {
			arg3 = args[3].(*PrependOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Prepend_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Prepend_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Prepend_Call) RunAndReturn(run func(collection *Collection, s string, bytes []byte, prependOptions *PrependOptions) (*MutationResult, error)) *mockKvProvider_Prepend_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Remove(collection *Collection, s string, removeOptions *RemoveOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, removeOptions)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *RemoveOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, removeOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, *RemoveOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, removeOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, *RemoveOptions) error); ok {
		r1 = returnFunc(collection, s, removeOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type mockKvProvider_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - removeOptions *RemoveOptions
func (_e *mockKvProvider_Expecter) Remove(collection interface{}, s interface{}, removeOptions interface{}) *mockKvProvider_Remove_Call {
	return &mockKvProvider_Remove_Call{Call: _e.mock.On("Remove", collection, s, removeOptions)}
}

func (_c *mockKvProvider_Remove_Call) Run(run func(collection *Collection, s string, removeOptions *RemoveOptions)) *mockKvProvider_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *RemoveOptions
		if args[2] != nil {
			arg2 = args[2].(*RemoveOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Remove_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Remove_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Remove_Call) RunAndReturn(run func(collection *Collection, s string, removeOptions *RemoveOptions) (*MutationResult, error)) *mockKvProvider_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Replace provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Replace(collection *Collection, s string, ifaceVal interface{}, replaceOptions *ReplaceOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, ifaceVal, replaceOptions)

	if len(ret) == 0 {
		panic("no return value specified for Replace")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *ReplaceOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, ifaceVal, replaceOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *ReplaceOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, ifaceVal, replaceOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, interface{}, *ReplaceOptions) error); ok {
		r1 = returnFunc(collection, s, ifaceVal, replaceOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Replace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Replace'
type mockKvProvider_Replace_Call struct {
	*mock.Call
}

// Replace is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - ifaceVal interface{}
//   - replaceOptions *ReplaceOptions
func (_e *mockKvProvider_Expecter) Replace(collection interface{}, s interface{}, ifaceVal interface{}, replaceOptions interface{}) *mockKvProvider_Replace_Call {
	return &mockKvProvider_Replace_Call{Call: _e.mock.On("Replace", collection, s, ifaceVal, replaceOptions)}
}

func (_c *mockKvProvider_Replace_Call) Run(run func(collection *Collection, s string, ifaceVal interface{}, replaceOptions *ReplaceOptions)) *mockKvProvider_Replace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *ReplaceOptions
		if args[3] != nil {
			arg3 = args[3].(*ReplaceOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Replace_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Replace_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Replace_Call) RunAndReturn(run func(collection *Collection, s string, ifaceVal interface{}, replaceOptions *ReplaceOptions) (*MutationResult, error)) *mockKvProvider_Replace_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Scan(collection *Collection, scanType ScanType, scanOptions *ScanOptions) (*ScanResult, error) {
	ret := _mock.Called(collection, scanType, scanOptions)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *ScanResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, ScanType, *ScanOptions) (*ScanResult, error)); ok {
		return returnFunc(collection, scanType, scanOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, ScanType, *ScanOptions) *ScanResult); ok {
		r0 = returnFunc(collection, scanType, scanOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ScanResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, ScanType, *ScanOptions) error); ok {
		r1 = returnFunc(collection, scanType, scanOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type mockKvProvider_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - collection *Collection
//   - scanType ScanType
//   - scanOptions *ScanOptions
func (_e *mockKvProvider_Expecter) Scan(collection interface{}, scanType interface{}, scanOptions interface{}) *mockKvProvider_Scan_Call {
	return &mockKvProvider_Scan_Call{Call: _e.mock.On("Scan", collection, scanType, scanOptions)}
}

func (_c *mockKvProvider_Scan_Call) Run(run func(collection *Collection, scanType ScanType, scanOptions *ScanOptions)) *mockKvProvider_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 ScanType
		if args[1] != nil {
			arg1 = args[1].(ScanType)
		}
		var arg2 *ScanOptions
		if args[2] != nil {
			arg2 = args[2].(*ScanOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_Scan_Call) Return(scanResult *ScanResult, err error) *mockKvProvider_Scan_Call {
	_c.Call.Return(scanResult, err)
	return _c
}

func (_c *mockKvProvider_Scan_Call) RunAndReturn(run func(collection *Collection, scanType ScanType, scanOptions *ScanOptions) (*ScanResult, error)) *mockKvProvider_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// StartKvOpTrace provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) StartKvOpTrace(collection *Collection, s string, requestSpan RequestSpan) *spanWrapper {
	ret := _mock.Called(collection, s, requestSpan)

	if len(ret) == 0 {
		panic("no return value specified for StartKvOpTrace")
	}

	var r0 *spanWrapper
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, RequestSpan) *spanWrapper); ok {
		r0 = returnFunc(collection, s, requestSpan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spanWrapper)
		}
	}
	return r0
}

// mockKvProvider_StartKvOpTrace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartKvOpTrace'
type mockKvProvider_StartKvOpTrace_Call struct {
	*mock.Call
}

// StartKvOpTrace is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - requestSpan RequestSpan
func (_e *mockKvProvider_Expecter) StartKvOpTrace(collection interface{}, s interface{}, requestSpan interface{}) *mockKvProvider_StartKvOpTrace_Call {
	return &mockKvProvider_StartKvOpTrace_Call{Call: _e.mock.On("StartKvOpTrace", collection, s, requestSpan)}
}

func (_c *mockKvProvider_StartKvOpTrace_Call) Run(run func(collection *Collection, s string, requestSpan RequestSpan)) *mockKvProvider_StartKvOpTrace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 RequestSpan
		if args[2] != nil {
			arg2 = args[2].(RequestSpan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockKvProvider_StartKvOpTrace_Call) Return(spanWrapperMoqParam *spanWrapper) *mockKvProvider_StartKvOpTrace_Call {
	_c.Call.Return(spanWrapperMoqParam)
	return _c
}

func (_c *mockKvProvider_StartKvOpTrace_Call) RunAndReturn(run func(collection *Collection, s string, requestSpan RequestSpan) *spanWrapper) *mockKvProvider_StartKvOpTrace_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Touch(collection *Collection, s string, duration time.Duration, touchOptions *TouchOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, duration, touchOptions)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *TouchOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, duration, touchOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, time.Duration, *TouchOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, duration, touchOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, time.Duration, *TouchOptions) error); ok {
		r1 = returnFunc(collection, s, duration, touchOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type mockKvProvider_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - duration time.Duration
//   - touchOptions *TouchOptions
func (_e *mockKvProvider_Expecter) Touch(collection interface{}, s interface{}, duration interface{}, touchOptions interface{}) *mockKvProvider_Touch_Call {
	return &mockKvProvider_Touch_Call{Call: _e.mock.On("Touch", collection, s, duration, touchOptions)}
}

func (_c *mockKvProvider_Touch_Call) Run(run func(collection *Collection, s string, duration time.Duration, touchOptions *TouchOptions)) *mockKvProvider_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 *TouchOptions
		if args[3] != nil {
			arg3 = args[3].(*TouchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Touch_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Touch_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Touch_Call) RunAndReturn(run func(collection *Collection, s string, duration time.Duration, touchOptions *TouchOptions) (*MutationResult, error)) *mockKvProvider_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Unlock(collection *Collection, s string, cas Cas, unlockOptions *UnlockOptions) error {
	ret := _mock.Called(collection, s, cas, unlockOptions)

	if len(ret) == 0 {
		panic("no return value specified for Unlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, Cas, *UnlockOptions) error); ok {
		r0 = returnFunc(collection, s, cas, unlockOptions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockKvProvider_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type mockKvProvider_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - cas Cas
//   - unlockOptions *UnlockOptions
func (_e *mockKvProvider_Expecter) Unlock(collection interface{}, s interface{}, cas interface{}, unlockOptions interface{}) *mockKvProvider_Unlock_Call {
	return &mockKvProvider_Unlock_Call{Call: _e.mock.On("Unlock", collection, s, cas, unlockOptions)}
}

func (_c *mockKvProvider_Unlock_Call) Run(run func(collection *Collection, s string, cas Cas, unlockOptions *UnlockOptions)) *mockKvProvider_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 Cas
		if args[2] != nil {
			arg2 = args[2].(Cas)
		}
		var arg3 *UnlockOptions
		if args[3] != nil {
			arg3 = args[3].(*UnlockOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Unlock_Call) Return(err error) *mockKvProvider_Unlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockKvProvider_Unlock_Call) RunAndReturn(run func(collection *Collection, s string, cas Cas, unlockOptions *UnlockOptions) error) *mockKvProvider_Unlock_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockKvProvider
func (_mock *mockKvProvider) Upsert(collection *Collection, s string, ifaceVal interface{}, upsertOptions *UpsertOptions) (*MutationResult, error) {
	ret := _mock.Called(collection, s, ifaceVal, upsertOptions)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *MutationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *UpsertOptions) (*MutationResult, error)); ok {
		return returnFunc(collection, s, ifaceVal, upsertOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(*Collection, string, interface{}, *UpsertOptions) *MutationResult); ok {
		r0 = returnFunc(collection, s, ifaceVal, upsertOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MutationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Collection, string, interface{}, *UpsertOptions) error); ok {
		r1 = returnFunc(collection, s, ifaceVal, upsertOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockKvProvider_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockKvProvider_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - collection *Collection
//   - s string
//   - ifaceVal interface{}
//   - upsertOptions *UpsertOptions
func (_e *mockKvProvider_Expecter) Upsert(collection interface{}, s interface{}, ifaceVal interface{}, upsertOptions interface{}) *mockKvProvider_Upsert_Call {
	return &mockKvProvider_Upsert_Call{Call: _e.mock.On("Upsert", collection, s, ifaceVal, upsertOptions)}
}

func (_c *mockKvProvider_Upsert_Call) Run(run func(collection *Collection, s string, ifaceVal interface{}, upsertOptions *UpsertOptions)) *mockKvProvider_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Collection
		if args[0] != nil {
			arg0 = args[0].(*Collection)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 *UpsertOptions
		if args[3] != nil {
			arg3 = args[3].(*UpsertOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockKvProvider_Upsert_Call) Return(mutationResult *MutationResult, err error) *mockKvProvider_Upsert_Call {
	_c.Call.Return(mutationResult, err)
	return _c
}

func (_c *mockKvProvider_Upsert_Call) RunAndReturn(run func(collection *Collection, s string, ifaceVal interface{}, upsertOptions *UpsertOptions) (*MutationResult, error)) *mockKvProvider_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
