// Code generated by mockery v2.52.2. DO NOT EDIT.

package gocb

import (
	gocbcore "github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// mockKvCapabilityVerifier is an autogenerated mock type for the kvCapabilityVerifier type
type mockKvCapabilityVerifier struct {
	mock.Mock
}

// BucketCapabilityStatus provides a mock function with given fields: cap
func (_m *mockKvCapabilityVerifier) BucketCapabilityStatus(cap gocbcore.BucketCapability) gocbcore.CapabilityStatus {
	ret := _m.Called(cap)

	if len(ret) == 0 {
		panic("no return value specified for BucketCapabilityStatus")
	}

	var r0 gocbcore.CapabilityStatus
	if rf, ok := ret.Get(0).(func(gocbcore.BucketCapability) gocbcore.CapabilityStatus); ok {
		r0 = rf(cap)
	} else {
		r0 = ret.Get(0).(gocbcore.CapabilityStatus)
	}

	return r0
}

// newMockKvCapabilityVerifier creates a new instance of mockKvCapabilityVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockKvCapabilityVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockKvCapabilityVerifier {
	mock := &mockKvCapabilityVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
