// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockQueryProviderCoreProvider creates a new instance of mockQueryProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockQueryProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockQueryProviderCoreProvider {
	mock := &mockQueryProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockQueryProviderCoreProvider is an autogenerated mock type for the queryProviderCoreProvider type
type mockQueryProviderCoreProvider struct {
	mock.Mock
}

type mockQueryProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockQueryProviderCoreProvider) EXPECT() *mockQueryProviderCoreProvider_Expecter {
	return &mockQueryProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// N1QLQuery provides a mock function for the type mockQueryProviderCoreProvider
func (_mock *mockQueryProviderCoreProvider) N1QLQuery(ctx context.Context, opts gocbcore.N1QLQueryOptions) (queryRowReader, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for N1QLQuery")
	}

	var r0 queryRowReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.N1QLQueryOptions) (queryRowReader, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.N1QLQueryOptions) queryRowReader); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryRowReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.N1QLQueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockQueryProviderCoreProvider_N1QLQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'N1QLQuery'
type mockQueryProviderCoreProvider_N1QLQuery_Call struct {
	*mock.Call
}

// N1QLQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.N1QLQueryOptions
func (_e *mockQueryProviderCoreProvider_Expecter) N1QLQuery(ctx interface{}, opts interface{}) *mockQueryProviderCoreProvider_N1QLQuery_Call {
	return &mockQueryProviderCoreProvider_N1QLQuery_Call{Call: _e.mock.On("N1QLQuery", ctx, opts)}
}

func (_c *mockQueryProviderCoreProvider_N1QLQuery_Call) Run(run func(ctx context.Context, opts gocbcore.N1QLQueryOptions)) *mockQueryProviderCoreProvider_N1QLQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.N1QLQueryOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.N1QLQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockQueryProviderCoreProvider_N1QLQuery_Call) Return(qOut queryRowReader, errOut error) *mockQueryProviderCoreProvider_N1QLQuery_Call {
	_c.Call.Return(qOut, errOut)
	return _c
}

func (_c *mockQueryProviderCoreProvider_N1QLQuery_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.N1QLQueryOptions) (queryRowReader, error)) *mockQueryProviderCoreProvider_N1QLQuery_Call {
	_c.Call.Return(run)
	return _c
}

// PreparedN1QLQuery provides a mock function for the type mockQueryProviderCoreProvider
func (_mock *mockQueryProviderCoreProvider) PreparedN1QLQuery(ctx context.Context, opts gocbcore.N1QLQueryOptions) (queryRowReader, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for PreparedN1QLQuery")
	}

	var r0 queryRowReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.N1QLQueryOptions) (queryRowReader, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.N1QLQueryOptions) queryRowReader); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryRowReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.N1QLQueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockQueryProviderCoreProvider_PreparedN1QLQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreparedN1QLQuery'
type mockQueryProviderCoreProvider_PreparedN1QLQuery_Call struct {
	*mock.Call
}

// PreparedN1QLQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.N1QLQueryOptions
func (_e *mockQueryProviderCoreProvider_Expecter) PreparedN1QLQuery(ctx interface{}, opts interface{}) *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call {
	return &mockQueryProviderCoreProvider_PreparedN1QLQuery_Call{Call: _e.mock.On("PreparedN1QLQuery", ctx, opts)}
}

func (_c *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call) Run(run func(ctx context.Context, opts gocbcore.N1QLQueryOptions)) *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.N1QLQueryOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.N1QLQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call) Return(qOut queryRowReader, errOut error) *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call {
	_c.Call.Return(qOut, errOut)
	return _c
}

func (_c *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.N1QLQueryOptions) (queryRowReader, error)) *mockQueryProviderCoreProvider_PreparedN1QLQuery_Call {
	_c.Call.Return(run)
	return _c
}
