// Code generated by mockery v1.0.0. DO NOT EDIT.

package gocb

import gocbcore "github.com/couchbase/gocbcore/v8"
import mock "github.com/stretchr/testify/mock"

// mockHttpProvider is an autogenerated mock type for the httpProvider type
type mockHttpProvider struct {
	mock.Mock
}

// DoHTTPRequest provides a mock function with given fields: req
func (_m *mockHttpProvider) DoHTTPRequest(req *gocbcore.HTTPRequest) (*gocbcore.HTTPResponse, error) {
	ret := _m.Called(req)

	var r0 *gocbcore.HTTPResponse
	if rf, ok := ret.Get(0).(func(*gocbcore.HTTPRequest) *gocbcore.HTTPResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocbcore.HTTPResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gocbcore.HTTPRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
