// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockSearchCapabilityVerifier creates a new instance of mockSearchCapabilityVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSearchCapabilityVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSearchCapabilityVerifier {
	mock := &mockSearchCapabilityVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSearchCapabilityVerifier is an autogenerated mock type for the searchCapabilityVerifier type
type mockSearchCapabilityVerifier struct {
	mock.Mock
}

type mockSearchCapabilityVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSearchCapabilityVerifier) EXPECT() *mockSearchCapabilityVerifier_Expecter {
	return &mockSearchCapabilityVerifier_Expecter{mock: &_m.Mock}
}

// SearchCapabilityStatus provides a mock function for the type mockSearchCapabilityVerifier
func (_mock *mockSearchCapabilityVerifier) SearchCapabilityStatus(cap gocbcore.SearchCapability) gocbcore.CapabilityStatus {
	ret := _mock.Called(cap)

	if len(ret) == 0 {
		panic("no return value specified for SearchCapabilityStatus")
	}

	var r0 gocbcore.CapabilityStatus
	if returnFunc, ok := ret.Get(0).(func(gocbcore.SearchCapability) gocbcore.CapabilityStatus); ok {
		r0 = returnFunc(cap)
	} else {
		r0 = ret.Get(0).(gocbcore.CapabilityStatus)
	}
	return r0
}

// mockSearchCapabilityVerifier_SearchCapabilityStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchCapabilityStatus'
type mockSearchCapabilityVerifier_SearchCapabilityStatus_Call struct {
	*mock.Call
}

// SearchCapabilityStatus is a helper method to define mock.On call
//   - cap gocbcore.SearchCapability
func (_e *mockSearchCapabilityVerifier_Expecter) SearchCapabilityStatus(cap interface{}) *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call {
	return &mockSearchCapabilityVerifier_SearchCapabilityStatus_Call{Call: _e.mock.On("SearchCapabilityStatus", cap)}
}

func (_c *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call) Run(run func(cap gocbcore.SearchCapability)) *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.SearchCapability
		if args[0] != nil {
			arg0 = args[0].(gocbcore.SearchCapability)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call) Return(capabilityStatus gocbcore.CapabilityStatus) *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call {
	_c.Call.Return(capabilityStatus)
	return _c
}

func (_c *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call) RunAndReturn(run func(cap gocbcore.SearchCapability) gocbcore.CapabilityStatus) *mockSearchCapabilityVerifier_SearchCapabilityStatus_Call {
	_c.Call.Return(run)
	return _c
}
