// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newMockWaitUntilReadyProvider creates a new instance of mockWaitUntilReadyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockWaitUntilReadyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockWaitUntilReadyProvider {
	mock := &mockWaitUntilReadyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockWaitUntilReadyProvider is an autogenerated mock type for the waitUntilReadyProvider type
type mockWaitUntilReadyProvider struct {
	mock.Mock
}

type mockWaitUntilReadyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockWaitUntilReadyProvider) EXPECT() *mockWaitUntilReadyProvider_Expecter {
	return &mockWaitUntilReadyProvider_Expecter{mock: &_m.Mock}
}

// WaitUntilReady provides a mock function for the type mockWaitUntilReadyProvider
func (_mock *mockWaitUntilReadyProvider) WaitUntilReady(ctx context.Context, deadline time.Time, opts *WaitUntilReadyOptions) error {
	ret := _mock.Called(ctx, deadline, opts)

	if len(ret) == 0 {
		panic("no return value specified for WaitUntilReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, *WaitUntilReadyOptions) error); ok {
		r0 = returnFunc(ctx, deadline, opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockWaitUntilReadyProvider_WaitUntilReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitUntilReady'
type mockWaitUntilReadyProvider_WaitUntilReady_Call struct {
	*mock.Call
}

// WaitUntilReady is a helper method to define mock.On call
//   - ctx context.Context
//   - deadline time.Time
//   - opts *WaitUntilReadyOptions
func (_e *mockWaitUntilReadyProvider_Expecter) WaitUntilReady(ctx interface{}, deadline interface{}, opts interface{}) *mockWaitUntilReadyProvider_WaitUntilReady_Call {
	return &mockWaitUntilReadyProvider_WaitUntilReady_Call{Call: _e.mock.On("WaitUntilReady", ctx, deadline, opts)}
}

func (_c *mockWaitUntilReadyProvider_WaitUntilReady_Call) Run(run func(ctx context.Context, deadline time.Time, opts *WaitUntilReadyOptions)) *mockWaitUntilReadyProvider_WaitUntilReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 *WaitUntilReadyOptions
		if args[2] != nil {
			arg2 = args[2].(*WaitUntilReadyOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockWaitUntilReadyProvider_WaitUntilReady_Call) Return(err error) *mockWaitUntilReadyProvider_WaitUntilReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockWaitUntilReadyProvider_WaitUntilReady_Call) RunAndReturn(run func(ctx context.Context, deadline time.Time, opts *WaitUntilReadyOptions) error) *mockWaitUntilReadyProvider_WaitUntilReady_Call {
	_c.Call.Return(run)
	return _c
}
