// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newMockMgmtProvider creates a new instance of mockMgmtProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockMgmtProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockMgmtProvider {
	mock := &mockMgmtProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockMgmtProvider is an autogenerated mock type for the mgmtProvider type
type mockMgmtProvider struct {
	mock.Mock
}

type mockMgmtProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockMgmtProvider) EXPECT() *mockMgmtProvider_Expecter {
	return &mockMgmtProvider_Expecter{mock: &_m.Mock}
}

// executeMgmtRequest provides a mock function for the type mockMgmtProvider
func (_mock *mockMgmtProvider) executeMgmtRequest(ctx context.Context, req mgmtRequest) (*mgmtResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for executeMgmtRequest")
	}

	var r0 *mgmtResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mgmtRequest) (*mgmtResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mgmtRequest) *mgmtResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgmtResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mgmtRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockMgmtProvider_executeMgmtRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'executeMgmtRequest'
type mockMgmtProvider_executeMgmtRequest_Call struct {
	*mock.Call
}

// executeMgmtRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req mgmtRequest
func (_e *mockMgmtProvider_Expecter) executeMgmtRequest(ctx interface{}, req interface{}) *mockMgmtProvider_executeMgmtRequest_Call {
	return &mockMgmtProvider_executeMgmtRequest_Call{Call: _e.mock.On("executeMgmtRequest", ctx, req)}
}

func (_c *mockMgmtProvider_executeMgmtRequest_Call) Run(run func(ctx context.Context, req mgmtRequest)) *mockMgmtProvider_executeMgmtRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mgmtRequest
		if args[1] != nil {
			arg1 = args[1].(mgmtRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockMgmtProvider_executeMgmtRequest_Call) Return(mgmtResponseMoqParam *mgmtResponse, err error) *mockMgmtProvider_executeMgmtRequest_Call {
	_c.Call.Return(mgmtResponseMoqParam, err)
	return _c
}

func (_c *mockMgmtProvider_executeMgmtRequest_Call) RunAndReturn(run func(ctx context.Context, req mgmtRequest) (*mgmtResponse, error)) *mockMgmtProvider_executeMgmtRequest_Call {
	_c.Call.Return(run)
	return _c
}
