// Code generated by mockery v1.0.0. DO NOT EDIT.

package gocb

import (
	gocbcore "github.com/couchbase/gocbcore/v9"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// mockWaitUntilReadyProvider is an autogenerated mock type for the waitUntilReadyProvider type
type mockWaitUntilReadyProvider struct {
	mock.Mock
}

// WaitUntilReady provides a mock function with given fields: deadline, opts
func (_m *mockWaitUntilReadyProvider) WaitUntilReady(deadline time.Time, opts gocbcore.WaitUntilReadyOptions) error {
	ret := _m.Called(deadline, opts)

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time, gocbcore.WaitUntilReadyOptions) error); ok {
		r0 = rf(deadline, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
