// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockViewProvider creates a new instance of mockViewProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockViewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockViewProvider {
	mock := &mockViewProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockViewProvider is an autogenerated mock type for the viewProvider type
type mockViewProvider struct {
	mock.Mock
}

type mockViewProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockViewProvider) EXPECT() *mockViewProvider_Expecter {
	return &mockViewProvider_Expecter{mock: &_m.Mock}
}

// ViewQuery provides a mock function for the type mockViewProvider
func (_mock *mockViewProvider) ViewQuery(designDoc string, viewName string, opts *ViewOptions) (*ViewResult, error) {
	ret := _mock.Called(designDoc, viewName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ViewQuery")
	}

	var r0 *ViewResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *ViewOptions) (*ViewResult, error)); ok {
		return returnFunc(designDoc, viewName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *ViewOptions) *ViewResult); ok {
		r0 = returnFunc(designDoc, viewName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ViewResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *ViewOptions) error); ok {
		r1 = returnFunc(designDoc, viewName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockViewProvider_ViewQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViewQuery'
type mockViewProvider_ViewQuery_Call struct {
	*mock.Call
}

// ViewQuery is a helper method to define mock.On call
//   - designDoc string
//   - viewName string
//   - opts *ViewOptions
func (_e *mockViewProvider_Expecter) ViewQuery(designDoc interface{}, viewName interface{}, opts interface{}) *mockViewProvider_ViewQuery_Call {
	return &mockViewProvider_ViewQuery_Call{Call: _e.mock.On("ViewQuery", designDoc, viewName, opts)}
}

func (_c *mockViewProvider_ViewQuery_Call) Run(run func(designDoc string, viewName string, opts *ViewOptions)) *mockViewProvider_ViewQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *ViewOptions
		if args[2] != nil {
			arg2 = args[2].(*ViewOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockViewProvider_ViewQuery_Call) Return(viewResult *ViewResult, err error) *mockViewProvider_ViewQuery_Call {
	_c.Call.Return(viewResult, err)
	return _c
}

func (_c *mockViewProvider_ViewQuery_Call) RunAndReturn(run func(designDoc string, viewName string, opts *ViewOptions) (*ViewResult, error)) *mockViewProvider_ViewQuery_Call {
	_c.Call.Return(run)
	return _c
}
