// Code generated by mockery v2.38.0. DO NOT EDIT.

package gocb

import (
	context "context"

	gocbcore "github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// mockAnalyticsProviderCoreProvider is an autogenerated mock type for the analyticsProviderCoreProvider type
type mockAnalyticsProviderCoreProvider struct {
	mock.Mock
}

// AnalyticsQuery provides a mock function with given fields: ctx, opts
func (_m *mockAnalyticsProviderCoreProvider) AnalyticsQuery(ctx context.Context, opts gocbcore.AnalyticsQueryOptions) (analyticsRowReader, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for AnalyticsQuery")
	}

	var r0 analyticsRowReader
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gocbcore.AnalyticsQueryOptions) (analyticsRowReader, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gocbcore.AnalyticsQueryOptions) analyticsRowReader); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyticsRowReader)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gocbcore.AnalyticsQueryOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockAnalyticsProviderCoreProvider creates a new instance of mockAnalyticsProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAnalyticsProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAnalyticsProviderCoreProvider {
	mock := &mockAnalyticsProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
