// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockAnalyticsProviderCoreProvider creates a new instance of mockAnalyticsProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAnalyticsProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAnalyticsProviderCoreProvider {
	mock := &mockAnalyticsProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAnalyticsProviderCoreProvider is an autogenerated mock type for the analyticsProviderCoreProvider type
type mockAnalyticsProviderCoreProvider struct {
	mock.Mock
}

type mockAnalyticsProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAnalyticsProviderCoreProvider) EXPECT() *mockAnalyticsProviderCoreProvider_Expecter {
	return &mockAnalyticsProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// AnalyticsQuery provides a mock function for the type mockAnalyticsProviderCoreProvider
func (_mock *mockAnalyticsProviderCoreProvider) AnalyticsQuery(ctx context.Context, opts gocbcore.AnalyticsQueryOptions) (analyticsRowReader, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for AnalyticsQuery")
	}

	var r0 analyticsRowReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.AnalyticsQueryOptions) (analyticsRowReader, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.AnalyticsQueryOptions) analyticsRowReader); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyticsRowReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.AnalyticsQueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyticsQuery'
type mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call struct {
	*mock.Call
}

// AnalyticsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.AnalyticsQueryOptions
func (_e *mockAnalyticsProviderCoreProvider_Expecter) AnalyticsQuery(ctx interface{}, opts interface{}) *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call {
	return &mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call{Call: _e.mock.On("AnalyticsQuery", ctx, opts)}
}

func (_c *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call) Run(run func(ctx context.Context, opts gocbcore.AnalyticsQueryOptions)) *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.AnalyticsQueryOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.AnalyticsQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call) Return(analyticsRowReaderMoqParam analyticsRowReader, err error) *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call {
	_c.Call.Return(analyticsRowReaderMoqParam, err)
	return _c
}

func (_c *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.AnalyticsQueryOptions) (analyticsRowReader, error)) *mockAnalyticsProviderCoreProvider_AnalyticsQuery_Call {
	_c.Call.Return(run)
	return _c
}
