// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockDiagnosticsProviderCoreProvider creates a new instance of mockDiagnosticsProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDiagnosticsProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDiagnosticsProviderCoreProvider {
	mock := &mockDiagnosticsProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockDiagnosticsProviderCoreProvider is an autogenerated mock type for the diagnosticsProviderCoreProvider type
type mockDiagnosticsProviderCoreProvider struct {
	mock.Mock
}

type mockDiagnosticsProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDiagnosticsProviderCoreProvider) EXPECT() *mockDiagnosticsProviderCoreProvider_Expecter {
	return &mockDiagnosticsProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// Diagnostics provides a mock function for the type mockDiagnosticsProviderCoreProvider
func (_mock *mockDiagnosticsProviderCoreProvider) Diagnostics(opts gocbcore.DiagnosticsOptions) (*gocbcore.DiagnosticInfo, error) {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for Diagnostics")
	}

	var r0 *gocbcore.DiagnosticInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(gocbcore.DiagnosticsOptions) (*gocbcore.DiagnosticInfo, error)); ok {
		return returnFunc(opts)
	}
	if returnFunc, ok := ret.Get(0).(func(gocbcore.DiagnosticsOptions) *gocbcore.DiagnosticInfo); ok {
		r0 = returnFunc(opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocbcore.DiagnosticInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(gocbcore.DiagnosticsOptions) error); ok {
		r1 = returnFunc(opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDiagnosticsProviderCoreProvider_Diagnostics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diagnostics'
type mockDiagnosticsProviderCoreProvider_Diagnostics_Call struct {
	*mock.Call
}

// Diagnostics is a helper method to define mock.On call
//   - opts gocbcore.DiagnosticsOptions
func (_e *mockDiagnosticsProviderCoreProvider_Expecter) Diagnostics(opts interface{}) *mockDiagnosticsProviderCoreProvider_Diagnostics_Call {
	return &mockDiagnosticsProviderCoreProvider_Diagnostics_Call{Call: _e.mock.On("Diagnostics", opts)}
}

func (_c *mockDiagnosticsProviderCoreProvider_Diagnostics_Call) Run(run func(opts gocbcore.DiagnosticsOptions)) *mockDiagnosticsProviderCoreProvider_Diagnostics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gocbcore.DiagnosticsOptions
		if args[0] != nil {
			arg0 = args[0].(gocbcore.DiagnosticsOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockDiagnosticsProviderCoreProvider_Diagnostics_Call) Return(diagnosticInfo *gocbcore.DiagnosticInfo, err error) *mockDiagnosticsProviderCoreProvider_Diagnostics_Call {
	_c.Call.Return(diagnosticInfo, err)
	return _c
}

func (_c *mockDiagnosticsProviderCoreProvider_Diagnostics_Call) RunAndReturn(run func(opts gocbcore.DiagnosticsOptions) (*gocbcore.DiagnosticInfo, error)) *mockDiagnosticsProviderCoreProvider_Diagnostics_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type mockDiagnosticsProviderCoreProvider
func (_mock *mockDiagnosticsProviderCoreProvider) Ping(ctx context.Context, opts gocbcore.PingOptions) (*gocbcore.PingResult, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *gocbcore.PingResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.PingOptions) (*gocbcore.PingResult, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.PingOptions) *gocbcore.PingResult); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocbcore.PingResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.PingOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockDiagnosticsProviderCoreProvider_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type mockDiagnosticsProviderCoreProvider_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.PingOptions
func (_e *mockDiagnosticsProviderCoreProvider_Expecter) Ping(ctx interface{}, opts interface{}) *mockDiagnosticsProviderCoreProvider_Ping_Call {
	return &mockDiagnosticsProviderCoreProvider_Ping_Call{Call: _e.mock.On("Ping", ctx, opts)}
}

func (_c *mockDiagnosticsProviderCoreProvider_Ping_Call) Run(run func(ctx context.Context, opts gocbcore.PingOptions)) *mockDiagnosticsProviderCoreProvider_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.PingOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.PingOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockDiagnosticsProviderCoreProvider_Ping_Call) Return(pingResult *gocbcore.PingResult, err error) *mockDiagnosticsProviderCoreProvider_Ping_Call {
	_c.Call.Return(pingResult, err)
	return _c
}

func (_c *mockDiagnosticsProviderCoreProvider_Ping_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.PingOptions) (*gocbcore.PingResult, error)) *mockDiagnosticsProviderCoreProvider_Ping_Call {
	_c.Call.Return(run)
	return _c
}
