// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockAnalyticsProvider creates a new instance of mockAnalyticsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAnalyticsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAnalyticsProvider {
	mock := &mockAnalyticsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAnalyticsProvider is an autogenerated mock type for the analyticsProvider type
type mockAnalyticsProvider struct {
	mock.Mock
}

type mockAnalyticsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAnalyticsProvider) EXPECT() *mockAnalyticsProvider_Expecter {
	return &mockAnalyticsProvider_Expecter{mock: &_m.Mock}
}

// AnalyticsQuery provides a mock function for the type mockAnalyticsProvider
func (_mock *mockAnalyticsProvider) AnalyticsQuery(statement string, scope *Scope, opts *AnalyticsOptions) (*AnalyticsResult, error) {
	ret := _mock.Called(statement, scope, opts)

	if len(ret) == 0 {
		panic("no return value specified for AnalyticsQuery")
	}

	var r0 *AnalyticsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *Scope, *AnalyticsOptions) (*AnalyticsResult, error)); ok {
		return returnFunc(statement, scope, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *Scope, *AnalyticsOptions) *AnalyticsResult); ok {
		r0 = returnFunc(statement, scope, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AnalyticsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *Scope, *AnalyticsOptions) error); ok {
		r1 = returnFunc(statement, scope, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAnalyticsProvider_AnalyticsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnalyticsQuery'
type mockAnalyticsProvider_AnalyticsQuery_Call struct {
	*mock.Call
}

// AnalyticsQuery is a helper method to define mock.On call
//   - statement string
//   - scope *Scope
//   - opts *AnalyticsOptions
func (_e *mockAnalyticsProvider_Expecter) AnalyticsQuery(statement interface{}, scope interface{}, opts interface{}) *mockAnalyticsProvider_AnalyticsQuery_Call {
	return &mockAnalyticsProvider_AnalyticsQuery_Call{Call: _e.mock.On("AnalyticsQuery", statement, scope, opts)}
}

func (_c *mockAnalyticsProvider_AnalyticsQuery_Call) Run(run func(statement string, scope *Scope, opts *AnalyticsOptions)) *mockAnalyticsProvider_AnalyticsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *Scope
		if args[1] != nil {
			arg1 = args[1].(*Scope)
		}
		var arg2 *AnalyticsOptions
		if args[2] != nil {
			arg2 = args[2].(*AnalyticsOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockAnalyticsProvider_AnalyticsQuery_Call) Return(analyticsResult *AnalyticsResult, err error) *mockAnalyticsProvider_AnalyticsQuery_Call {
	_c.Call.Return(analyticsResult, err)
	return _c
}

func (_c *mockAnalyticsProvider_AnalyticsQuery_Call) RunAndReturn(run func(statement string, scope *Scope, opts *AnalyticsOptions) (*AnalyticsResult, error)) *mockAnalyticsProvider_AnalyticsQuery_Call {
	_c.Call.Return(run)
	return _c
}
