// Code generated by mockery v1.0.0. DO NOT EDIT.

package gocb

import gocbcore "github.com/couchbase/gocbcore/v8"
import mock "github.com/stretchr/testify/mock"

// mockClusterCapabilityProvider is an autogenerated mock type for the clusterCapabilityProvider type
type mockClusterCapabilityProvider struct {
	mock.Mock
}

// SupportsClusterCapability provides a mock function with given fields: capability
func (_m *mockClusterCapabilityProvider) SupportsClusterCapability(capability gocbcore.ClusterCapability) bool {
	ret := _m.Called(capability)

	var r0 bool
	if rf, ok := ret.Get(0).(func(gocbcore.ClusterCapability) bool); ok {
		r0 = rf(capability)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
