// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"context"

	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockSearchProviderCoreProvider creates a new instance of mockSearchProviderCoreProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSearchProviderCoreProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSearchProviderCoreProvider {
	mock := &mockSearchProviderCoreProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSearchProviderCoreProvider is an autogenerated mock type for the searchProviderCoreProvider type
type mockSearchProviderCoreProvider struct {
	mock.Mock
}

type mockSearchProviderCoreProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSearchProviderCoreProvider) EXPECT() *mockSearchProviderCoreProvider_Expecter {
	return &mockSearchProviderCoreProvider_Expecter{mock: &_m.Mock}
}

// SearchQuery provides a mock function for the type mockSearchProviderCoreProvider
func (_mock *mockSearchProviderCoreProvider) SearchQuery(ctx context.Context, opts gocbcore.SearchQueryOptions) (searchRowReader, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchQuery")
	}

	var r0 searchRowReader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.SearchQueryOptions) (searchRowReader, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, gocbcore.SearchQueryOptions) searchRowReader); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(searchRowReader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, gocbcore.SearchQueryOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSearchProviderCoreProvider_SearchQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchQuery'
type mockSearchProviderCoreProvider_SearchQuery_Call struct {
	*mock.Call
}

// SearchQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - opts gocbcore.SearchQueryOptions
func (_e *mockSearchProviderCoreProvider_Expecter) SearchQuery(ctx interface{}, opts interface{}) *mockSearchProviderCoreProvider_SearchQuery_Call {
	return &mockSearchProviderCoreProvider_SearchQuery_Call{Call: _e.mock.On("SearchQuery", ctx, opts)}
}

func (_c *mockSearchProviderCoreProvider_SearchQuery_Call) Run(run func(ctx context.Context, opts gocbcore.SearchQueryOptions)) *mockSearchProviderCoreProvider_SearchQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 gocbcore.SearchQueryOptions
		if args[1] != nil {
			arg1 = args[1].(gocbcore.SearchQueryOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockSearchProviderCoreProvider_SearchQuery_Call) Return(searchRowReaderMoqParam searchRowReader, err error) *mockSearchProviderCoreProvider_SearchQuery_Call {
	_c.Call.Return(searchRowReaderMoqParam, err)
	return _c
}

func (_c *mockSearchProviderCoreProvider_SearchQuery_Call) RunAndReturn(run func(ctx context.Context, opts gocbcore.SearchQueryOptions) (searchRowReader, error)) *mockSearchProviderCoreProvider_SearchQuery_Call {
	_c.Call.Return(run)
	return _c
}
