// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"github.com/couchbase/gocb/v2/search"
	mock "github.com/stretchr/testify/mock"
)

// newMockSearchProvider creates a new instance of mockSearchProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSearchProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSearchProvider {
	mock := &mockSearchProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockSearchProvider is an autogenerated mock type for the searchProvider type
type mockSearchProvider struct {
	mock.Mock
}

type mockSearchProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSearchProvider) EXPECT() *mockSearchProvider_Expecter {
	return &mockSearchProvider_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type mockSearchProvider
func (_mock *mockSearchProvider) Search(scope *Scope, indexName string, request SearchRequest, opts *SearchOptions) (*SearchResult, error) {
	ret := _mock.Called(scope, indexName, request, opts)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Scope, string, SearchRequest, *SearchOptions) (*SearchResult, error)); ok {
		return returnFunc(scope, indexName, request, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(*Scope, string, SearchRequest, *SearchOptions) *SearchResult); ok {
		r0 = returnFunc(scope, indexName, request, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Scope, string, SearchRequest, *SearchOptions) error); ok {
		r1 = returnFunc(scope, indexName, request, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSearchProvider_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type mockSearchProvider_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - scope *Scope
//   - indexName string
//   - request SearchRequest
//   - opts *SearchOptions
func (_e *mockSearchProvider_Expecter) Search(scope interface{}, indexName interface{}, request interface{}, opts interface{}) *mockSearchProvider_Search_Call {
	return &mockSearchProvider_Search_Call{Call: _e.mock.On("Search", scope, indexName, request, opts)}
}

func (_c *mockSearchProvider_Search_Call) Run(run func(scope *Scope, indexName string, request SearchRequest, opts *SearchOptions)) *mockSearchProvider_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Scope
		if args[0] != nil {
			arg0 = args[0].(*Scope)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 SearchRequest
		if args[2] != nil {
			arg2 = args[2].(SearchRequest)
		}
		var arg3 *SearchOptions
		if args[3] != nil {
			arg3 = args[3].(*SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockSearchProvider_Search_Call) Return(searchResult *SearchResult, err error) *mockSearchProvider_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *mockSearchProvider_Search_Call) RunAndReturn(run func(scope *Scope, indexName string, request SearchRequest, opts *SearchOptions) (*SearchResult, error)) *mockSearchProvider_Search_Call {
	_c.Call.Return(run)
	return _c
}

// SearchQuery provides a mock function for the type mockSearchProvider
func (_mock *mockSearchProvider) SearchQuery(indexName string, query search.Query, opts *SearchOptions) (*SearchResult, error) {
	ret := _mock.Called(indexName, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchQuery")
	}

	var r0 *SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, search.Query, *SearchOptions) (*SearchResult, error)); ok {
		return returnFunc(indexName, query, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, search.Query, *SearchOptions) *SearchResult); ok {
		r0 = returnFunc(indexName, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, search.Query, *SearchOptions) error); ok {
		r1 = returnFunc(indexName, query, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockSearchProvider_SearchQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchQuery'
type mockSearchProvider_SearchQuery_Call struct {
	*mock.Call
}

// SearchQuery is a helper method to define mock.On call
//   - indexName string
//   - query search.Query
//   - opts *SearchOptions
func (_e *mockSearchProvider_Expecter) SearchQuery(indexName interface{}, query interface{}, opts interface{}) *mockSearchProvider_SearchQuery_Call {
	return &mockSearchProvider_SearchQuery_Call{Call: _e.mock.On("SearchQuery", indexName, query, opts)}
}

func (_c *mockSearchProvider_SearchQuery_Call) Run(run func(indexName string, query search.Query, opts *SearchOptions)) *mockSearchProvider_SearchQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 search.Query
		if args[1] != nil {
			arg1 = args[1].(search.Query)
		}
		var arg2 *SearchOptions
		if args[2] != nil {
			arg2 = args[2].(*SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockSearchProvider_SearchQuery_Call) Return(searchResult *SearchResult, err error) *mockSearchProvider_SearchQuery_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *mockSearchProvider_SearchQuery_Call) RunAndReturn(run func(indexName string, query search.Query, opts *SearchOptions) (*SearchResult, error)) *mockSearchProvider_SearchQuery_Call {
	_c.Call.Return(run)
	return _c
}
