// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gocb

import (
	"github.com/couchbase/gocbcore/v10"
	mock "github.com/stretchr/testify/mock"
)

// newMockConnectionManager creates a new instance of mockConnectionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConnectionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConnectionManager {
	mock := &mockConnectionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockConnectionManager is an autogenerated mock type for the connectionManager type
type mockConnectionManager struct {
	mock.Mock
}

type mockConnectionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConnectionManager) EXPECT() *mockConnectionManager_Expecter {
	return &mockConnectionManager_Expecter{mock: &_m.Mock}
}

// MarkOpBeginning provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) MarkOpBeginning() {
	_mock.Called()
	return
}

// mockConnectionManager_MarkOpBeginning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOpBeginning'
type mockConnectionManager_MarkOpBeginning_Call struct {
	*mock.Call
}

// MarkOpBeginning is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) MarkOpBeginning() *mockConnectionManager_MarkOpBeginning_Call {
	return &mockConnectionManager_MarkOpBeginning_Call{Call: _e.mock.On("MarkOpBeginning")}
}

func (_c *mockConnectionManager_MarkOpBeginning_Call) Run(run func()) *mockConnectionManager_MarkOpBeginning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_MarkOpBeginning_Call) Return() *mockConnectionManager_MarkOpBeginning_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConnectionManager_MarkOpBeginning_Call) RunAndReturn(run func()) *mockConnectionManager_MarkOpBeginning_Call {
	_c.Run(run)
	return _c
}

// MarkOpCompleted provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) MarkOpCompleted() {
	_mock.Called()
	return
}

// mockConnectionManager_MarkOpCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOpCompleted'
type mockConnectionManager_MarkOpCompleted_Call struct {
	*mock.Call
}

// MarkOpCompleted is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) MarkOpCompleted() *mockConnectionManager_MarkOpCompleted_Call {
	return &mockConnectionManager_MarkOpCompleted_Call{Call: _e.mock.On("MarkOpCompleted")}
}

func (_c *mockConnectionManager_MarkOpCompleted_Call) Run(run func()) *mockConnectionManager_MarkOpCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_MarkOpCompleted_Call) Return() *mockConnectionManager_MarkOpCompleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConnectionManager_MarkOpCompleted_Call) RunAndReturn(run func()) *mockConnectionManager_MarkOpCompleted_Call {
	_c.Run(run)
	return _c
}

// SetAuthenticator provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) SetAuthenticator(opts SetAuthenticatorOptions) error {
	ret := _mock.Called(opts)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthenticator")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(SetAuthenticatorOptions) error); ok {
		r0 = returnFunc(opts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionManager_SetAuthenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthenticator'
type mockConnectionManager_SetAuthenticator_Call struct {
	*mock.Call
}

// SetAuthenticator is a helper method to define mock.On call
//   - opts SetAuthenticatorOptions
func (_e *mockConnectionManager_Expecter) SetAuthenticator(opts interface{}) *mockConnectionManager_SetAuthenticator_Call {
	return &mockConnectionManager_SetAuthenticator_Call{Call: _e.mock.On("SetAuthenticator", opts)}
}

func (_c *mockConnectionManager_SetAuthenticator_Call) Run(run func(opts SetAuthenticatorOptions)) *mockConnectionManager_SetAuthenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 SetAuthenticatorOptions
		if args[0] != nil {
			arg0 = args[0].(SetAuthenticatorOptions)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_SetAuthenticator_Call) Return(err error) *mockConnectionManager_SetAuthenticator_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionManager_SetAuthenticator_Call) RunAndReturn(run func(opts SetAuthenticatorOptions) error) *mockConnectionManager_SetAuthenticator_Call {
	_c.Call.Return(run)
	return _c
}

// close provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionManager_close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'close'
type mockConnectionManager_close_Call struct {
	*mock.Call
}

// close is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) close() *mockConnectionManager_close_Call {
	return &mockConnectionManager_close_Call{Call: _e.mock.On("close")}
}

func (_c *mockConnectionManager_close_Call) Run(run func()) *mockConnectionManager_close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_close_Call) Return(err error) *mockConnectionManager_close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionManager_close_Call) RunAndReturn(run func() error) *mockConnectionManager_close_Call {
	_c.Call.Return(run)
	return _c
}

// connection provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) connection(bucketName string) (*gocbcore.Agent, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for connection")
	}

	var r0 *gocbcore.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*gocbcore.Agent, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *gocbcore.Agent); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocbcore.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'connection'
type mockConnectionManager_connection_Call struct {
	*mock.Call
}

// connection is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) connection(bucketName interface{}) *mockConnectionManager_connection_Call {
	return &mockConnectionManager_connection_Call{Call: _e.mock.On("connection", bucketName)}
}

func (_c *mockConnectionManager_connection_Call) Run(run func(bucketName string)) *mockConnectionManager_connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_connection_Call) Return(agent *gocbcore.Agent, err error) *mockConnectionManager_connection_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *mockConnectionManager_connection_Call) RunAndReturn(run func(bucketName string) (*gocbcore.Agent, error)) *mockConnectionManager_connection_Call {
	_c.Call.Return(run)
	return _c
}

// getAnalyticsIndexProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getAnalyticsIndexProvider() (analyticsIndexProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAnalyticsIndexProvider")
	}

	var r0 analyticsIndexProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (analyticsIndexProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() analyticsIndexProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyticsIndexProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getAnalyticsIndexProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAnalyticsIndexProvider'
type mockConnectionManager_getAnalyticsIndexProvider_Call struct {
	*mock.Call
}

// getAnalyticsIndexProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getAnalyticsIndexProvider() *mockConnectionManager_getAnalyticsIndexProvider_Call {
	return &mockConnectionManager_getAnalyticsIndexProvider_Call{Call: _e.mock.On("getAnalyticsIndexProvider")}
}

func (_c *mockConnectionManager_getAnalyticsIndexProvider_Call) Run(run func()) *mockConnectionManager_getAnalyticsIndexProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getAnalyticsIndexProvider_Call) Return(analyticsIndexProviderMoqParam analyticsIndexProvider, err error) *mockConnectionManager_getAnalyticsIndexProvider_Call {
	_c.Call.Return(analyticsIndexProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getAnalyticsIndexProvider_Call) RunAndReturn(run func() (analyticsIndexProvider, error)) *mockConnectionManager_getAnalyticsIndexProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getAnalyticsProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getAnalyticsProvider() (analyticsProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getAnalyticsProvider")
	}

	var r0 analyticsProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (analyticsProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() analyticsProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyticsProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getAnalyticsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getAnalyticsProvider'
type mockConnectionManager_getAnalyticsProvider_Call struct {
	*mock.Call
}

// getAnalyticsProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getAnalyticsProvider() *mockConnectionManager_getAnalyticsProvider_Call {
	return &mockConnectionManager_getAnalyticsProvider_Call{Call: _e.mock.On("getAnalyticsProvider")}
}

func (_c *mockConnectionManager_getAnalyticsProvider_Call) Run(run func()) *mockConnectionManager_getAnalyticsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getAnalyticsProvider_Call) Return(analyticsProviderMoqParam analyticsProvider, err error) *mockConnectionManager_getAnalyticsProvider_Call {
	_c.Call.Return(analyticsProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getAnalyticsProvider_Call) RunAndReturn(run func() (analyticsProvider, error)) *mockConnectionManager_getAnalyticsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getBucketManagementProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getBucketManagementProvider() (bucketManagementProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getBucketManagementProvider")
	}

	var r0 bucketManagementProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bucketManagementProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bucketManagementProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bucketManagementProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getBucketManagementProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getBucketManagementProvider'
type mockConnectionManager_getBucketManagementProvider_Call struct {
	*mock.Call
}

// getBucketManagementProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getBucketManagementProvider() *mockConnectionManager_getBucketManagementProvider_Call {
	return &mockConnectionManager_getBucketManagementProvider_Call{Call: _e.mock.On("getBucketManagementProvider")}
}

func (_c *mockConnectionManager_getBucketManagementProvider_Call) Run(run func()) *mockConnectionManager_getBucketManagementProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getBucketManagementProvider_Call) Return(bucketManagementProviderMoqParam bucketManagementProvider, err error) *mockConnectionManager_getBucketManagementProvider_Call {
	_c.Call.Return(bucketManagementProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getBucketManagementProvider_Call) RunAndReturn(run func() (bucketManagementProvider, error)) *mockConnectionManager_getBucketManagementProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getCollectionsManagementProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getCollectionsManagementProvider(bucketName string) (collectionsManagementProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getCollectionsManagementProvider")
	}

	var r0 collectionsManagementProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (collectionsManagementProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) collectionsManagementProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(collectionsManagementProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getCollectionsManagementProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getCollectionsManagementProvider'
type mockConnectionManager_getCollectionsManagementProvider_Call struct {
	*mock.Call
}

// getCollectionsManagementProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getCollectionsManagementProvider(bucketName interface{}) *mockConnectionManager_getCollectionsManagementProvider_Call {
	return &mockConnectionManager_getCollectionsManagementProvider_Call{Call: _e.mock.On("getCollectionsManagementProvider", bucketName)}
}

func (_c *mockConnectionManager_getCollectionsManagementProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getCollectionsManagementProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getCollectionsManagementProvider_Call) Return(collectionsManagementProviderMoqParam collectionsManagementProvider, err error) *mockConnectionManager_getCollectionsManagementProvider_Call {
	_c.Call.Return(collectionsManagementProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getCollectionsManagementProvider_Call) RunAndReturn(run func(bucketName string) (collectionsManagementProvider, error)) *mockConnectionManager_getCollectionsManagementProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getDiagnosticsProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getDiagnosticsProvider(bucketName string) (diagnosticsProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getDiagnosticsProvider")
	}

	var r0 diagnosticsProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (diagnosticsProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) diagnosticsProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(diagnosticsProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getDiagnosticsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getDiagnosticsProvider'
type mockConnectionManager_getDiagnosticsProvider_Call struct {
	*mock.Call
}

// getDiagnosticsProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getDiagnosticsProvider(bucketName interface{}) *mockConnectionManager_getDiagnosticsProvider_Call {
	return &mockConnectionManager_getDiagnosticsProvider_Call{Call: _e.mock.On("getDiagnosticsProvider", bucketName)}
}

func (_c *mockConnectionManager_getDiagnosticsProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getDiagnosticsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getDiagnosticsProvider_Call) Return(diagnosticsProviderMoqParam diagnosticsProvider, err error) *mockConnectionManager_getDiagnosticsProvider_Call {
	_c.Call.Return(diagnosticsProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getDiagnosticsProvider_Call) RunAndReturn(run func(bucketName string) (diagnosticsProvider, error)) *mockConnectionManager_getDiagnosticsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getEventingManagementProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getEventingManagementProvider() (eventingManagementProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getEventingManagementProvider")
	}

	var r0 eventingManagementProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (eventingManagementProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() eventingManagementProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eventingManagementProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getEventingManagementProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getEventingManagementProvider'
type mockConnectionManager_getEventingManagementProvider_Call struct {
	*mock.Call
}

// getEventingManagementProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getEventingManagementProvider() *mockConnectionManager_getEventingManagementProvider_Call {
	return &mockConnectionManager_getEventingManagementProvider_Call{Call: _e.mock.On("getEventingManagementProvider")}
}

func (_c *mockConnectionManager_getEventingManagementProvider_Call) Run(run func()) *mockConnectionManager_getEventingManagementProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getEventingManagementProvider_Call) Return(eventingManagementProviderMoqParam eventingManagementProvider, err error) *mockConnectionManager_getEventingManagementProvider_Call {
	_c.Call.Return(eventingManagementProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getEventingManagementProvider_Call) RunAndReturn(run func() (eventingManagementProvider, error)) *mockConnectionManager_getEventingManagementProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getHTTPProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getHTTPProvider(bucketName string) (httpProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getHTTPProvider")
	}

	var r0 httpProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (httpProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) httpProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getHTTPProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getHTTPProvider'
type mockConnectionManager_getHTTPProvider_Call struct {
	*mock.Call
}

// getHTTPProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getHTTPProvider(bucketName interface{}) *mockConnectionManager_getHTTPProvider_Call {
	return &mockConnectionManager_getHTTPProvider_Call{Call: _e.mock.On("getHTTPProvider", bucketName)}
}

func (_c *mockConnectionManager_getHTTPProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getHTTPProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getHTTPProvider_Call) Return(httpProviderMoqParam httpProvider, err error) *mockConnectionManager_getHTTPProvider_Call {
	_c.Call.Return(httpProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getHTTPProvider_Call) RunAndReturn(run func(bucketName string) (httpProvider, error)) *mockConnectionManager_getHTTPProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getInternalProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getInternalProvider() (internalProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getInternalProvider")
	}

	var r0 internalProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (internalProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() internalProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(internalProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getInternalProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getInternalProvider'
type mockConnectionManager_getInternalProvider_Call struct {
	*mock.Call
}

// getInternalProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getInternalProvider() *mockConnectionManager_getInternalProvider_Call {
	return &mockConnectionManager_getInternalProvider_Call{Call: _e.mock.On("getInternalProvider")}
}

func (_c *mockConnectionManager_getInternalProvider_Call) Run(run func()) *mockConnectionManager_getInternalProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getInternalProvider_Call) Return(internalProviderMoqParam internalProvider, err error) *mockConnectionManager_getInternalProvider_Call {
	_c.Call.Return(internalProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getInternalProvider_Call) RunAndReturn(run func() (internalProvider, error)) *mockConnectionManager_getInternalProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getKvBulkProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getKvBulkProvider(bucketName string) (kvBulkProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getKvBulkProvider")
	}

	var r0 kvBulkProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (kvBulkProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) kvBulkProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kvBulkProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getKvBulkProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getKvBulkProvider'
type mockConnectionManager_getKvBulkProvider_Call struct {
	*mock.Call
}

// getKvBulkProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getKvBulkProvider(bucketName interface{}) *mockConnectionManager_getKvBulkProvider_Call {
	return &mockConnectionManager_getKvBulkProvider_Call{Call: _e.mock.On("getKvBulkProvider", bucketName)}
}

func (_c *mockConnectionManager_getKvBulkProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getKvBulkProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getKvBulkProvider_Call) Return(kvBulkProviderMoqParam kvBulkProvider, err error) *mockConnectionManager_getKvBulkProvider_Call {
	_c.Call.Return(kvBulkProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getKvBulkProvider_Call) RunAndReturn(run func(bucketName string) (kvBulkProvider, error)) *mockConnectionManager_getKvBulkProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getKvCapabilitiesProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getKvCapabilitiesProvider(bucketName string) (kvCapabilityVerifier, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getKvCapabilitiesProvider")
	}

	var r0 kvCapabilityVerifier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (kvCapabilityVerifier, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) kvCapabilityVerifier); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kvCapabilityVerifier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getKvCapabilitiesProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getKvCapabilitiesProvider'
type mockConnectionManager_getKvCapabilitiesProvider_Call struct {
	*mock.Call
}

// getKvCapabilitiesProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getKvCapabilitiesProvider(bucketName interface{}) *mockConnectionManager_getKvCapabilitiesProvider_Call {
	return &mockConnectionManager_getKvCapabilitiesProvider_Call{Call: _e.mock.On("getKvCapabilitiesProvider", bucketName)}
}

func (_c *mockConnectionManager_getKvCapabilitiesProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getKvCapabilitiesProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getKvCapabilitiesProvider_Call) Return(kvCapabilityVerifierMoqParam kvCapabilityVerifier, err error) *mockConnectionManager_getKvCapabilitiesProvider_Call {
	_c.Call.Return(kvCapabilityVerifierMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getKvCapabilitiesProvider_Call) RunAndReturn(run func(bucketName string) (kvCapabilityVerifier, error)) *mockConnectionManager_getKvCapabilitiesProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getKvProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getKvProvider(bucketName string) (kvProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getKvProvider")
	}

	var r0 kvProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (kvProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) kvProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kvProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getKvProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getKvProvider'
type mockConnectionManager_getKvProvider_Call struct {
	*mock.Call
}

// getKvProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getKvProvider(bucketName interface{}) *mockConnectionManager_getKvProvider_Call {
	return &mockConnectionManager_getKvProvider_Call{Call: _e.mock.On("getKvProvider", bucketName)}
}

func (_c *mockConnectionManager_getKvProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getKvProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getKvProvider_Call) Return(kvProviderMoqParam kvProvider, err error) *mockConnectionManager_getKvProvider_Call {
	_c.Call.Return(kvProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getKvProvider_Call) RunAndReturn(run func(bucketName string) (kvProvider, error)) *mockConnectionManager_getKvProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getMeter provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getMeter() *meterWrapper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getMeter")
	}

	var r0 *meterWrapper
	if returnFunc, ok := ret.Get(0).(func() *meterWrapper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meterWrapper)
		}
	}
	return r0
}

// mockConnectionManager_getMeter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getMeter'
type mockConnectionManager_getMeter_Call struct {
	*mock.Call
}

// getMeter is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getMeter() *mockConnectionManager_getMeter_Call {
	return &mockConnectionManager_getMeter_Call{Call: _e.mock.On("getMeter")}
}

func (_c *mockConnectionManager_getMeter_Call) Run(run func()) *mockConnectionManager_getMeter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getMeter_Call) Return(meterWrapperMoqParam *meterWrapper) *mockConnectionManager_getMeter_Call {
	_c.Call.Return(meterWrapperMoqParam)
	return _c
}

func (_c *mockConnectionManager_getMeter_Call) RunAndReturn(run func() *meterWrapper) *mockConnectionManager_getMeter_Call {
	_c.Call.Return(run)
	return _c
}

// getQueryIndexProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getQueryIndexProvider() (queryIndexProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getQueryIndexProvider")
	}

	var r0 queryIndexProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (queryIndexProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() queryIndexProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryIndexProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getQueryIndexProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getQueryIndexProvider'
type mockConnectionManager_getQueryIndexProvider_Call struct {
	*mock.Call
}

// getQueryIndexProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getQueryIndexProvider() *mockConnectionManager_getQueryIndexProvider_Call {
	return &mockConnectionManager_getQueryIndexProvider_Call{Call: _e.mock.On("getQueryIndexProvider")}
}

func (_c *mockConnectionManager_getQueryIndexProvider_Call) Run(run func()) *mockConnectionManager_getQueryIndexProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getQueryIndexProvider_Call) Return(queryIndexProviderMoqParam queryIndexProvider, err error) *mockConnectionManager_getQueryIndexProvider_Call {
	_c.Call.Return(queryIndexProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getQueryIndexProvider_Call) RunAndReturn(run func() (queryIndexProvider, error)) *mockConnectionManager_getQueryIndexProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getQueryProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getQueryProvider() (queryProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getQueryProvider")
	}

	var r0 queryProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (queryProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() queryProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(queryProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getQueryProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getQueryProvider'
type mockConnectionManager_getQueryProvider_Call struct {
	*mock.Call
}

// getQueryProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getQueryProvider() *mockConnectionManager_getQueryProvider_Call {
	return &mockConnectionManager_getQueryProvider_Call{Call: _e.mock.On("getQueryProvider")}
}

func (_c *mockConnectionManager_getQueryProvider_Call) Run(run func()) *mockConnectionManager_getQueryProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getQueryProvider_Call) Return(queryProviderMoqParam queryProvider, err error) *mockConnectionManager_getQueryProvider_Call {
	_c.Call.Return(queryProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getQueryProvider_Call) RunAndReturn(run func() (queryProvider, error)) *mockConnectionManager_getQueryProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getSearchCapabilitiesProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getSearchCapabilitiesProvider() (searchCapabilityVerifier, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSearchCapabilitiesProvider")
	}

	var r0 searchCapabilityVerifier
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (searchCapabilityVerifier, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() searchCapabilityVerifier); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(searchCapabilityVerifier)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getSearchCapabilitiesProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSearchCapabilitiesProvider'
type mockConnectionManager_getSearchCapabilitiesProvider_Call struct {
	*mock.Call
}

// getSearchCapabilitiesProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getSearchCapabilitiesProvider() *mockConnectionManager_getSearchCapabilitiesProvider_Call {
	return &mockConnectionManager_getSearchCapabilitiesProvider_Call{Call: _e.mock.On("getSearchCapabilitiesProvider")}
}

func (_c *mockConnectionManager_getSearchCapabilitiesProvider_Call) Run(run func()) *mockConnectionManager_getSearchCapabilitiesProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getSearchCapabilitiesProvider_Call) Return(searchCapabilityVerifierMoqParam searchCapabilityVerifier, err error) *mockConnectionManager_getSearchCapabilitiesProvider_Call {
	_c.Call.Return(searchCapabilityVerifierMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getSearchCapabilitiesProvider_Call) RunAndReturn(run func() (searchCapabilityVerifier, error)) *mockConnectionManager_getSearchCapabilitiesProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getSearchIndexProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getSearchIndexProvider() (searchIndexProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSearchIndexProvider")
	}

	var r0 searchIndexProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (searchIndexProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() searchIndexProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(searchIndexProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getSearchIndexProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSearchIndexProvider'
type mockConnectionManager_getSearchIndexProvider_Call struct {
	*mock.Call
}

// getSearchIndexProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getSearchIndexProvider() *mockConnectionManager_getSearchIndexProvider_Call {
	return &mockConnectionManager_getSearchIndexProvider_Call{Call: _e.mock.On("getSearchIndexProvider")}
}

func (_c *mockConnectionManager_getSearchIndexProvider_Call) Run(run func()) *mockConnectionManager_getSearchIndexProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getSearchIndexProvider_Call) Return(searchIndexProviderMoqParam searchIndexProvider, err error) *mockConnectionManager_getSearchIndexProvider_Call {
	_c.Call.Return(searchIndexProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getSearchIndexProvider_Call) RunAndReturn(run func() (searchIndexProvider, error)) *mockConnectionManager_getSearchIndexProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getSearchProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getSearchProvider() (searchProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSearchProvider")
	}

	var r0 searchProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (searchProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() searchProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(searchProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getSearchProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSearchProvider'
type mockConnectionManager_getSearchProvider_Call struct {
	*mock.Call
}

// getSearchProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getSearchProvider() *mockConnectionManager_getSearchProvider_Call {
	return &mockConnectionManager_getSearchProvider_Call{Call: _e.mock.On("getSearchProvider")}
}

func (_c *mockConnectionManager_getSearchProvider_Call) Run(run func()) *mockConnectionManager_getSearchProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getSearchProvider_Call) Return(searchProviderMoqParam searchProvider, err error) *mockConnectionManager_getSearchProvider_Call {
	_c.Call.Return(searchProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getSearchProvider_Call) RunAndReturn(run func() (searchProvider, error)) *mockConnectionManager_getSearchProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getTransactionsProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getTransactionsProvider() (transactionsProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getTransactionsProvider")
	}

	var r0 transactionsProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transactionsProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transactionsProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transactionsProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getTransactionsProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getTransactionsProvider'
type mockConnectionManager_getTransactionsProvider_Call struct {
	*mock.Call
}

// getTransactionsProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getTransactionsProvider() *mockConnectionManager_getTransactionsProvider_Call {
	return &mockConnectionManager_getTransactionsProvider_Call{Call: _e.mock.On("getTransactionsProvider")}
}

func (_c *mockConnectionManager_getTransactionsProvider_Call) Run(run func()) *mockConnectionManager_getTransactionsProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getTransactionsProvider_Call) Return(transactionsProviderMoqParam transactionsProvider, err error) *mockConnectionManager_getTransactionsProvider_Call {
	_c.Call.Return(transactionsProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getTransactionsProvider_Call) RunAndReturn(run func() (transactionsProvider, error)) *mockConnectionManager_getTransactionsProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getUserManagerProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getUserManagerProvider() (userManagerProvider, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getUserManagerProvider")
	}

	var r0 userManagerProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (userManagerProvider, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() userManagerProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(userManagerProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getUserManagerProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getUserManagerProvider'
type mockConnectionManager_getUserManagerProvider_Call struct {
	*mock.Call
}

// getUserManagerProvider is a helper method to define mock.On call
func (_e *mockConnectionManager_Expecter) getUserManagerProvider() *mockConnectionManager_getUserManagerProvider_Call {
	return &mockConnectionManager_getUserManagerProvider_Call{Call: _e.mock.On("getUserManagerProvider")}
}

func (_c *mockConnectionManager_getUserManagerProvider_Call) Run(run func()) *mockConnectionManager_getUserManagerProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConnectionManager_getUserManagerProvider_Call) Return(userManagerProviderMoqParam userManagerProvider, err error) *mockConnectionManager_getUserManagerProvider_Call {
	_c.Call.Return(userManagerProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getUserManagerProvider_Call) RunAndReturn(run func() (userManagerProvider, error)) *mockConnectionManager_getUserManagerProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getViewIndexProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getViewIndexProvider(bucketName string) (viewIndexProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getViewIndexProvider")
	}

	var r0 viewIndexProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (viewIndexProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) viewIndexProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(viewIndexProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getViewIndexProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getViewIndexProvider'
type mockConnectionManager_getViewIndexProvider_Call struct {
	*mock.Call
}

// getViewIndexProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getViewIndexProvider(bucketName interface{}) *mockConnectionManager_getViewIndexProvider_Call {
	return &mockConnectionManager_getViewIndexProvider_Call{Call: _e.mock.On("getViewIndexProvider", bucketName)}
}

func (_c *mockConnectionManager_getViewIndexProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getViewIndexProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getViewIndexProvider_Call) Return(viewIndexProviderMoqParam viewIndexProvider, err error) *mockConnectionManager_getViewIndexProvider_Call {
	_c.Call.Return(viewIndexProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getViewIndexProvider_Call) RunAndReturn(run func(bucketName string) (viewIndexProvider, error)) *mockConnectionManager_getViewIndexProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getViewProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getViewProvider(bucketName string) (viewProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getViewProvider")
	}

	var r0 viewProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (viewProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) viewProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(viewProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getViewProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getViewProvider'
type mockConnectionManager_getViewProvider_Call struct {
	*mock.Call
}

// getViewProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getViewProvider(bucketName interface{}) *mockConnectionManager_getViewProvider_Call {
	return &mockConnectionManager_getViewProvider_Call{Call: _e.mock.On("getViewProvider", bucketName)}
}

func (_c *mockConnectionManager_getViewProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getViewProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getViewProvider_Call) Return(viewProviderMoqParam viewProvider, err error) *mockConnectionManager_getViewProvider_Call {
	_c.Call.Return(viewProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getViewProvider_Call) RunAndReturn(run func(bucketName string) (viewProvider, error)) *mockConnectionManager_getViewProvider_Call {
	_c.Call.Return(run)
	return _c
}

// getWaitUntilReadyProvider provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) getWaitUntilReadyProvider(bucketName string) (waitUntilReadyProvider, error) {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for getWaitUntilReadyProvider")
	}

	var r0 waitUntilReadyProvider
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (waitUntilReadyProvider, error)); ok {
		return returnFunc(bucketName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) waitUntilReadyProvider); ok {
		r0 = returnFunc(bucketName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(waitUntilReadyProvider)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bucketName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockConnectionManager_getWaitUntilReadyProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getWaitUntilReadyProvider'
type mockConnectionManager_getWaitUntilReadyProvider_Call struct {
	*mock.Call
}

// getWaitUntilReadyProvider is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) getWaitUntilReadyProvider(bucketName interface{}) *mockConnectionManager_getWaitUntilReadyProvider_Call {
	return &mockConnectionManager_getWaitUntilReadyProvider_Call{Call: _e.mock.On("getWaitUntilReadyProvider", bucketName)}
}

func (_c *mockConnectionManager_getWaitUntilReadyProvider_Call) Run(run func(bucketName string)) *mockConnectionManager_getWaitUntilReadyProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_getWaitUntilReadyProvider_Call) Return(waitUntilReadyProviderMoqParam waitUntilReadyProvider, err error) *mockConnectionManager_getWaitUntilReadyProvider_Call {
	_c.Call.Return(waitUntilReadyProviderMoqParam, err)
	return _c
}

func (_c *mockConnectionManager_getWaitUntilReadyProvider_Call) RunAndReturn(run func(bucketName string) (waitUntilReadyProvider, error)) *mockConnectionManager_getWaitUntilReadyProvider_Call {
	_c.Call.Return(run)
	return _c
}

// initTransactions provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) initTransactions(cluster *Cluster) error {
	ret := _mock.Called(cluster)

	if len(ret) == 0 {
		panic("no return value specified for initTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*Cluster) error); ok {
		r0 = returnFunc(cluster)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionManager_initTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'initTransactions'
type mockConnectionManager_initTransactions_Call struct {
	*mock.Call
}

// initTransactions is a helper method to define mock.On call
//   - cluster *Cluster
func (_e *mockConnectionManager_Expecter) initTransactions(cluster interface{}) *mockConnectionManager_initTransactions_Call {
	return &mockConnectionManager_initTransactions_Call{Call: _e.mock.On("initTransactions", cluster)}
}

func (_c *mockConnectionManager_initTransactions_Call) Run(run func(cluster *Cluster)) *mockConnectionManager_initTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Cluster
		if args[0] != nil {
			arg0 = args[0].(*Cluster)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_initTransactions_Call) Return(err error) *mockConnectionManager_initTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionManager_initTransactions_Call) RunAndReturn(run func(cluster *Cluster) error) *mockConnectionManager_initTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// openBucket provides a mock function for the type mockConnectionManager
func (_mock *mockConnectionManager) openBucket(bucketName string) error {
	ret := _mock.Called(bucketName)

	if len(ret) == 0 {
		panic("no return value specified for openBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(bucketName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockConnectionManager_openBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'openBucket'
type mockConnectionManager_openBucket_Call struct {
	*mock.Call
}

// openBucket is a helper method to define mock.On call
//   - bucketName string
func (_e *mockConnectionManager_Expecter) openBucket(bucketName interface{}) *mockConnectionManager_openBucket_Call {
	return &mockConnectionManager_openBucket_Call{Call: _e.mock.On("openBucket", bucketName)}
}

func (_c *mockConnectionManager_openBucket_Call) Run(run func(bucketName string)) *mockConnectionManager_openBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockConnectionManager_openBucket_Call) Return(err error) *mockConnectionManager_openBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockConnectionManager_openBucket_Call) RunAndReturn(run func(bucketName string) error) *mockConnectionManager_openBucket_Call {
	_c.Call.Return(run)
	return _c
}
